-- ============================================================
-- PHASE 51 — IT AUTOMATION LIST HR MASTER SYNC (corrected)
-- Generated from data/it_automation_list.psv.
-- Re-run scripts/generate_it_automation_sync.mjs after source changes.
--
-- FIXES vs prior version:
--  1. Row-count error (212 vs 215): the source VALUES block was missing
--     sn 137 and sn 214-215. Rebuilt from the authoritative 215-row
--     export — all 215 rows now present, sn 1..215 contiguous.
--  2. Duplicate staff_id hard-abort: the source data genuinely contains
--     two Staff IDs each shared by two different employees
--     (IMFB/20/0147: SIMON TUNDE ADEMOLA vs OBASOYIN AYOKUNLE JOSEPH;
--      IMFB/23/0305: AJILORE ODUNOLA ESTHER vs ANOCHILI FAVOUR ADANNA).
--     This is an HR data-entry conflict, not an import bug — picking a
--     winner automatically would silently misassign one employee's
--     record to the other. Fix: those 4 conflicting rows are excluded
--     from the employee upsert and reported at the end as
--     "duplicate_staff_id_conflicts_excluded" for manual HR resolution.
--     The other 211 rows import normally.
-- ============================================================

begin;

create temporary table _it_automation_source (
  sn integer not null,
  staff_id text not null,
  full_name text not null,
  confirmation_status text not null,
  designation text not null,
  department text not null,
  branch_name text not null,
  gender text,
  email text,
  supervisor1 text,
  supervisor2 text,
  supervisor3 text
) on commit preserve rows;

insert into _it_automation_source (
  sn, staff_id, full_name, confirmation_status, designation, department,
  branch_name, gender, email, supervisor1, supervisor2, supervisor3
) values
  (1, 'IMFB/05/0002', 'UGBERAESE SIMEON', 'CONFIRMED', 'CREDIT ADMIN OFFICER', 'RISK & COMPLIANCE', 'HEAD OFFICE', 'M', 's.ugberaese@infinitymfb.com', 'AYOLADE MOYINOLUWA', 'ABIWON TOLULOPE', 'GABRIEL OLUDOTUN ADEWUNMI'),
  (2, 'IMFB/06/0003', 'OKIRIWENWEN WILSON OVIE', 'CONFIRMED', 'HEAD, INFORMATION TECHNOLOGY', 'INFORMATION TECHNOLOGY', 'HEAD OFFICE', 'M', 'w.ovie@infinitymfb.com', 'GABRIEL OLUDOTUN ADEWUNMI', null, null),
  (3, 'IMFB/07/0004', 'OJABINENI MOSUNMOLA AINA', 'CONFIRMED', 'AREA MANAGER (AREA 5)', 'CREDIT & MARKETING', 'IKORODU', 'F', 'm.ojabineni@infinitymfb.com', 'OLANAOKA OLANREWAJU YEMISI', 'GABRIEL OLUDOTUN ADEWUNMI', null),
  (4, 'IMFB/08/0005', 'OLOWOLABI MODUPE', 'CONFIRMED', 'CASH OFFICER', 'OPERATIONS', 'HEAD OFFICE', 'F', 'm.olowolabi@infinitymfb.com', 'EVELYN OGHENEFEJIRO UGUTE', 'GABRIEL OLUDOTUN ADEWUNMI', null),
  (5, 'IMFB/08/0006', 'DUKIYA-GBALEYIDAGBA OMOTAYO JANET', 'CONFIRMED', 'CREDIT ADMIN OFFICER', 'RISK & COMPLIANCE', 'HEAD OFFICE', 'F', 'o.dukiya@infinitymfb.com', 'AYOLADE MOYINOLUWA', 'ABIWON TOLULOPE', 'GABRIEL OLUDOTUN ADEWUNMI'),
  (6, 'IMFB/MD/0001', 'ADEWUNMI GABRIEL OLUDOTUN', 'CONFIRMED', 'MD/CEO', 'MD/CEO', 'HEAD OFFICE', 'M', 'g.adewunmi@infinitymfb.com', 'BOD', null, null),
  (7, 'IMFB/09/0010', 'AYOLADE MOYINOLUWA ADEWUNMI', 'CONFIRMED', 'UNIT HEAD, CREDIT ADMIN', 'RISK & COMPLIANCE', 'HEAD OFFICE', 'F', 'm.ayolade@infinitymfb.com', 'ABIWON TOLULOPE', 'GABRIEL OLUDOTUN ADEWUNMI', null),
  (8, 'IMFB/09/0012', 'BANKOLE TEMITOPE RUTH', 'CONFIRMED', 'CHIEF COMPLIANCE OFFICER', 'RISK & COMPLIANCE', 'OWODE', 'F', 't.bankole@infinitymfb.com', 'ABIWON TOLULOPE', 'GABRIEL OLUDOTUN ADEWUNMI', null),
  (9, 'IMFB/10/0013', 'OLANAOKA OLANREWAJU YEMISI', 'CONFIRMED', 'HEAD, INDIVIDUAL LOAN', 'CREDIT & MARKETING', 'HEAD OFFICE', 'F', 'l.olanaoka@infinitymfb.com', 'GABRIEL OLUDOTUN ADEWUNMI', null, null),
  (10, 'IMFB/10/0015', 'DISU HANNAH HALIMAT', 'CONFIRMED', 'BRANCH MANAGER', 'CREDIT & MARKETING', 'KETU', 'F', 'h.disu@infinitymfb.com', 'ADENLE ADEWALE OLUWAROTIMI', 'OLANAOKA OLANREWAJU YEMISI', 'GABRIEL OLUDOTUN ADEWUNMI'),
  (11, 'IMFB/10/0016', 'ALONGE MARIAM ABIODUN', 'CONFIRMED', 'BRANCH MANAGER', 'CREDIT & MARKETING', 'MUSHIN', 'F', 'm.alonge@infinitymfb.com', 'OBILOR IFEANYIN', 'OLANAOKA OLANREWAJU YEMISI', 'GABRIEL OLUDOTUN ADEWUNMI'),
  (12, 'IMFB/11/0019', 'AIKULOLA ADETUTU OLORUNTOBA', 'CONFIRMED', 'COMPLIANCE OFFICER', 'RISK & COMPLIANCE', 'ODOGUNYAN', 'F', 'a.aikulola@infinitymfb.com', 'BANKOLE TEMITOPE', 'ABIWON TOLULOPE', 'GABRIEL OLUDOTUN ADEWUNMI'),
  (13, 'IMFB/11/0020', 'OLAYEMI ODUNOLA MULIKAT', 'CONFIRMED', 'UNIT HEAD, ''WHOLESALE LENDING', 'CREDIT & MARKETING', 'LAGOS ISLAND 2', 'F', 'o.olayemi@infinitymfb.com', 'AJISEGBEDE GBEMI', 'GABRIEL OLUDOTUN ADEWUNMI', null),
  (14, 'IMFB/11/0022', 'ABIWON TOLULOPE AYODEJI', 'CONFIRMED', 'HEAD, RISK ENTERPRISE & MGT', 'RISK & COMPLIANCE', 'HEAD OFFICE', 'M', 't.abiwon@infinitymfb.com', 'GABRIEL OLUDOTUN ADEWUNMI', null, null),
  (15, 'IMFB/12/0024', 'OKODUA REXONA', 'CONFIRMED', 'BRANCH MANAGER', 'CREDIT & MARKETING', 'IKEJA', 'F', 'r.okodua@infinitymfb.com', 'OBILOR IFEANYIN', 'OLANAOKA OLANREWAJU YEMISI', 'GABRIEL OLUDOTUN ADEWUNMI'),
  (16, 'IMFB/12/0025', 'OLOMU FUNMILAYO OLUBUNMI', 'CONFIRMED', 'OPERATIONS OFFICER', 'OPERATIONS', 'IKORODU', 'F', 'f.olomu@infinitymfb.com', 'EVELYN OGHENEFEJIRO UGUTE', 'GABRIEL OLUDOTUN ADEWUNMI', null),
  (17, 'IMFB/12/0027', 'ILORI ADEOLA DAVIDSON', 'CONFIRMED', 'INFORMATION TECHNOLOGY OFFICER', 'INFORMATION TECHNOLOGY', 'HEAD OFFICE', 'M', 'a.ilori@infinitymfb.com', 'WILSON OVIE OKIRIWENWEN', 'GABRIEL OLUDOTUN ADEWUNMI', null),
  (18, 'IMFB/12/0029', 'AJAYI OLUWABUKOLA ANDREW', 'CONFIRMED', 'ADMINISTRATION OFFICER', 'ADMINISTRATION', 'HEAD OFFICE', 'M', 'o.ajayi@infinitymfb.com', 'ORUSOSO  ISIOMA-NWALIGBE', 'GABRIEL OLUDOTUN ADEWUNMI', null),
  (19, 'IMFB/13/0031', 'OBIOHA ANNE CHIDIMMA', 'CONFIRMED', 'AREA MANAGER (AREA 2)', 'CREDIT & MARKETING', 'LAGOS ISLAND 1', 'F', 'a.nwosu@infinitymfb.com', 'OLANAOKA OLANREWAJU YEMISI', 'GABRIEL OLUDOTUN ADEWUNMI', null),
  (20, 'IMFB/13/0033', 'UKUAGHE JUDE OAMEN', 'CONFIRMED', 'UNIT HEAD, WHOLESALE LENDING', 'CREDIT & MARKETING', 'HEAD OFFICE', 'M', 'j.ukuaghe@infinitymfb.com', 'AJISEGBEDE GBEMI', 'ABIWON TOLULOPE', 'GABRIEL OLUDOTUN ADEWUNMI'),
  (21, 'IMFB/13/0037', 'BABATUNDE BUSAYO MARY', 'CONFIRMED', 'CUSTOMER SERVICE OFFICER', 'OPERATIONS', 'BARIGA', 'F', 'b.babatunde@infinitymfb.com', 'EVELYN OGHENEFEJIRO UGUTE', 'GABRIEL OLUDOTUN ADEWUNMI', null),
  (22, 'IMFB/14/0039', 'OGBECHIE FRANCIS ADIM', 'CONFIRMED', 'AUDIT & INVESTIGATION OFFICER', 'AUDIT & INVESTIGATION', 'HEAD OFFICE', 'M', 'f.obechie@infinitymfb.com', 'OLADELE MUTIU SALAMI', 'GABRIEL OLUDOTUN ADEWUNMI', null),
  (23, 'IMFB/14/0040', 'ADINOGE ESTHER FUNMILAYO', 'CONFIRMED', 'BRANCH MANAGER', 'CREDIT & MARKETING', 'AGEGE', 'F', 'e.adinoge@infinitymfb.com', 'ADENLE ADEWALE OLUWAROTIMI', 'OLANAOKA OLANREWAJU YEMISI', 'GABRIEL OLUDOTUN ADEWUNMI'),
  (24, 'IMFB/14/0041', 'NWACHUKWU ANNE CHILE', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'OSHODI', 'F', 'a.nwachukwu@infinitymfb.com', 'IHUOMA GLORIA ENYINNAYA', 'OBILOR IFEANYI', 'OLANAOKA OLANREWAJU YEMISI'),
  (25, 'IMFB/14/0042', 'SALAMI OLADELE MUTIU', 'CONFIRMED', 'HEAD, AUDIT & INVESTIGATION', 'AUDIT & INVESTIGATION', 'HEAD OFFICE', 'M', 'o.salami@infinitymfb.com', 'GABRIEL OLUDOTUN ADEWUNMI', null, null),
  (26, 'IMFB/14/0046', 'AJAYI SAMUEL FOLORUNSHO', 'CONFIRMED', 'UNIT HEAD, ACCOUNT', 'FINANCIAL CONTROL', 'HEAD OFFICE', 'M', 'sa.folorunsho@infinitymfb.com', 'OYELERE OLAYIDE AKANJI', 'GABRIEL OLUDOTUN ADEWUNMI', null),
  (27, 'IMFB/15/0048', 'OSEMEKE OMORODION ROXY', 'CONFIRMED', 'SENIOR LOAN OFFICER', 'CREDIT & MARKETING', 'HEAD OFFICE', 'M', 'o.omorodion@infinitymfb.com', 'ONUMAJULU VICTOR', 'ADENLE ADEWALE OLUWAROTIMI', 'OLANAOKA OLANREWAJU YEMISI'),
  (28, 'IMFB/15/0049', 'OBILOR IFEANYI SAMSON', 'CONFIRMED', 'AREA MANAGER (AREA 1)', 'CREDIT & MARKETING', 'OSHODI', 'M', 'if.obilor@infinitymfb.com', 'OLANAOKA OLANREWAJU YEMISI', 'GABRIEL OLUDOTUN ADEWUNMI', null),
  (29, 'IMFB/15/0051', 'YUSUFF BUSAYO DANIEL', 'CONFIRMED', 'AUDIT & INVESTIGATION OFFICER', 'AUDIT & INVESTIGATION', 'HEAD OFFICE', 'M', 'b.yusuff@infinitymfb.com', 'OLADELE MUTIU SALAMI', 'GABRIEL OLUDOTUN ADEWUNMI', null),
  (30, 'IMFB/15/0053', 'AJISEGBEDE GBEMILEKE ABIGAIL', 'CONFIRMED', 'HEAD, WHOLESALE LENDING TEAM', 'CREDIT & MARKETING', 'HEAD OFFICE', 'F', 'g.ajisegbede@infinitymfb.com', 'GABRIEL OLUDOTUN ADEWUNMI', 'MCC', null),
  (31, 'IMFB/16/0055', 'OMITOLA MARIAM OLABISI', 'CONFIRMED', 'TELLER', 'OPERATIONS', 'LAGOS ISLAND 1', 'F', 'm.omitola@infinitymfb.com', 'UGUTE FEJIRO', null, null),
  (32, 'IMFB/16/0057', 'OGUNFOWORA OMOTAYO SUNDAY', 'CONFIRMED', 'BRANCH MANAGER', 'CREDIT & MARKETING', 'ODOGUNYAN', 'M', 'o.ogunfowora@infinitymfb.com', 'OJABINENI MOSUN', 'OLANAOKA OLANREWAJU YEMISI', null),
  (33, 'IMFB/16/0063', 'ODEPO SHOLA ADEMIDUN', 'CONFIRMED', 'BRANCH MANAGER', 'CREDIT & MARKETING', 'IKORODU', 'F', 's.odepo@infinitymfb.com', 'OJABINENI MOSUN', 'OLANAOKA OLANREWAJU YEMISI', null),
  (34, 'IMFB/17/0066', 'INYANG LUCY MMAYEN', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'HEAD OFFICE', 'F', 'l.nyang@infinitymfb.com', 'ONUMAJULU VICTOR', 'ADENLE ADEWALE OLUWAROTIMI', 'OLANAOKA OLANREWAJU YEMISI'),
  (35, 'IMFB/17/0068', 'RAJI (AYORINDE) OLUWATOMI KAFAYAT', 'CONFIRMED', 'OPERATIONS OFFICER', 'OPERATIONS', 'IKEJA', 'F', 'k.raji@infinitymfb.com', 'UGUTE FEJIRO', null, null),
  (36, 'IMFB/17/0070', 'UMUKORO KELECHI JULIE', 'CONFIRMED', 'P.A. TO BOD', 'ADMINISTRATION', 'HEAD OFFICE', 'F', 'k.umukoro@infinitymfb.com', 'BOD', null, null),
  (37, 'IMFB/17/0071', 'AWOTALE TEMITOPE SERAH', 'CONFIRMED', 'OPERATIONS OFFICER', 'OPERATIONS', 'OWODE', 'F', 't.awotale@infinitymfb.com', 'UGUTE FEJIRO', null, null),
  (38, 'IMFB/17/0072', 'UVOH OBIANUJU ADAOBI', 'CONFIRMED', 'COMPLIANCE OFFICER', 'RISK & COMPLIANCE', 'IKORODU', 'F', 'o.uvoh@infinitymfb.com', 'BANKOLE TEMITOPE', 'ABIWON TOLULOPE', 'GABRIEL OLUDOTUN ADEWUNMI'),
  (39, 'IMFB/17/0075', 'OGUNBADEJO MUSA ADENIYI', 'CONFIRMED', 'DRIVER', 'ADMINISTRATION', 'HEAD OFFICE', 'M', 'N/A', 'ORUSOSO  ISIOMA-NWALIGBE', 'GABRIEL OLUDOTUN ADEWUNMI', null),
  (40, 'IMFB/17/0076', 'OYETUNDE YEMI TAWA', 'CONFIRMED', 'TELLER POSTING', 'OPERATIONS', 'HEAD OFFICE', 'F', 'y.oyetunde@infinitymfb.com', 'UGUTE FEJIRO', null, null),
  (41, 'IMFB/17/0078', 'OLAYINKA KAZEEM OLASUNKANMI', 'CONFIRMED', 'DRIVER', 'ADMINISTRATION', 'HEAD OFFICE', 'M', 'N/A', 'ORUSOSO  ISIOMA-NWALIGBE', 'GABRIEL OLUDOTUN ADEWUNMI', null),
  (42, 'IMFB/18/0079', 'FATEYE KEHINDE MARY', 'CONFIRMED', 'UNIT HEAD, RISK', 'RISK & COMPLIANCE', 'HEAD OFFICE', 'F', 'k.fateye@inifintymfb.com', 'ABIWON TOLULOPE', 'GABRIEL OLUDOTUN ADEWUNMI', null),
  (43, 'IMFB/18/0081', 'OGUNSOLA (HAMMED) ADEOLA SAIDAT', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'ODOGUNYAN', 'F', 's.hammed@infinitymfb.com', 'OGUNFOWORA OMOTAYO', 'OJABINENI MOSUN', 'OLANAOKA OLANREWAJU YEMISI'),
  (44, 'IMFB/18/0083', 'OLASANJO TOYIN AINA', 'CONFIRMED', 'BRANCH MANAGER', 'CREDIT & MARKETING', 'OWODE', 'F', 't.olasanjo@infinitymfb.com', 'OJABINENI MOSUN', 'OLANAOKA OLANREWAJU YEMISI', null),
  (45, 'IMFB/18/0084', 'ODIGWE OLUCHI CHARITINA', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'ODOGUNYAN', 'F', 'o.odigwe@infinitymfb.com', 'OGUNFOWORA OMOTAYO', 'OJABINENI MOSUN', 'OLANAOKA OLANREWAJU YEMISI'),
  (46, 'IMFB/18/0086', 'AJIBOYE BUKOLA RACHEAL', 'CONFIRMED', 'CUSTOMER SERVICE OFFICER', 'OPERATIONS', 'ODOGUNYAN', 'F', 'r.ajiboye@infinitymfb.com', 'UGUTE FEJIRO', null, null),
  (47, 'IMFB/18/0088', 'YAKUBU IDRIS', 'CONFIRMED', 'DISPATCH', 'ADMINISTRATION', 'HEAD OFFICE', 'M', 'N/A', 'ORUSOSO  ISIOMA-NWALIGBE', 'GMD/MD.HRM', null),
  (48, 'IMFB/18/0091', 'ABEGUNDE OLUSHOLA AKINTUNDE', 'CONFIRMED', 'COMPLIANCE OFFICER', 'RISK & COMPLIANCE', 'LAGOS ISLAND 2/IBEJU -LEKKI/AJAH', 'M', 'o.abegunde@infinitymfb.com', 'BANKOLE TEMITOPE', 'ABIWON TOLULOPE', 'GABRIEL OLUDOTUN ADEWUNMI'),
  (49, 'IMFB/18/0092', 'NWANKWO BLESSING CHIAMAKA', 'CONFIRMED', 'OPERATIONS OFFICER', 'OPERATIONS', 'OSHODI', 'F', 'b.nwankwo@infinitymfb.com', 'UGUTE FEJIRO', null, null),
  (50, 'IMFB/19/0098', 'OTESILE FATAI SEUN', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'ILE-EPO', 'M', 's.oteshile@infinitymfb.com', 'AGUKWE PECULIAR', 'OJABINENI MOSUN', 'OLANAOKA OLANREWAJU YEMISI'),
  (51, 'IMFB/19/0101', 'ATIKU TAWAKALITU HOPE', 'CONFIRMED', 'BRANCH MANAGER', 'CREDIT & MARKETING', 'BARIGA', 'F', 'h.atiku@infinitymfb.com', 'ADENLE ADEWALE OLUWAROTIMI', 'OLANAOKA OLANREWAJU YEMISI', null),
  (52, 'IMFB/19/0103', 'TAIWO GIDEON OMOYEMI', 'CONFIRMED', 'RISK OFFICER', 'RISK & COMPLIANCE', 'HEAD OFFICE', 'M', 'g.taiwo@infinitymfb.com', 'FATEYE KEHINDE', 'ABIWON TOLULOPE', null),
  (53, 'IMFB/19/0104', 'ODEJAYI OPEYEMI OLUMAYOKUN', 'CONFIRMED', 'ACCOUNTS OFFICER', 'FINANCIAL CONTROL', 'HEAD OFFICE', 'M', 'o.odejayi@infinitymfb.com', 'AJAYI SAMUEL', 'OYELERE OLAYIDE', 'GABRIEL OLUDOTUN ADEWUNMI'),
  (54, 'IMFB/19/0106', 'DANIEL ANNY UDO', 'CONFIRMED', 'LOAN MONITORING & RECOVERY OFFICER', 'LOAN MONITORING & RECOVERY', 'HEAD OFFICE', 'F', 'a.daniel@infinitymfb.com', 'ABIWON TOLULOPE', null, null),
  (55, 'IMFB/19/0108', 'UCHE BLESSING NGOZIKA', 'CONFIRMED', 'CUSTOMER SERVICE OFFICER', 'OPERATIONS', 'SABO/YABA', 'F', 'n.uche@infinitymfb.com', 'UGUTE FEJIRO', null, null),
  (56, 'IMFB/19/0110', 'ADENLE ADEWALE OLUWAROTIMI', 'CONFIRMED', 'AREA MANAGER (AREA 3)', 'CREDIT & MARKETING', 'HEAD OFFICE', 'M', 'a.adenle@infinitymfb.com', 'OLANAOKA OLANREWAJU YEMISI', 'GABRIEL OLUDOTUN ADEWUNMI', null),
  (57, 'IMFB/19/0115', 'ADIGUN BOLANLE VICTORIA', 'CONFIRMED', 'OPERATIONS OFFICER', 'OPERATIONS', 'AGEGE', 'F', 'v.adigun@infinitymfb.com', 'UGUTE FEJIRO', null, null),
  (58, 'IMFB/19/0118', 'OLANASE (SHOKOYA) GRACE ODUNAYO', 'CONFIRMED', 'BRANCH MANAGER', 'CREDIT & MARKETING', 'IKORODU', 'F', 'g.olanase@infinitymfb.com', 'OJABINENI MOSUN', 'OLANAOKA OLANREWAJU YEMISI', 'GABRIEL OLUDOTUN ADEWUNMI'),
  (59, 'IMFB/20/0121', 'FAGBUARO VICTOR OLUKAYODE', 'CONFIRMED', 'UNIT HEAD, RECOVER/AG. BRANCH MANAGER', 'RISK & COMPLIANCE', 'KOLA', 'M', 'v.fagbuaro@infinitymfb.com', 'ABIWON TOLULOPE', null, null),
  (60, 'IMFB/20/0124', 'IKHUREIGBE EMMANUEL EROMOSELE', 'CONFIRMED', 'HR OFFICER', 'HUMAN RESOURCES', 'HEAD OFFICE', 'M', 'e.ikhureigbe@imfimitymfb.com', 'OHAEGBU AWELE VICTORIA', 'GABRIEL OLUDOTUN ADEWUNMI', null),
  (61, 'IMFB/20/0127', 'OZIOKO COSMAS IKECHUKWU', 'CONFIRMED', 'HEAD, E-BUSINESS', 'E-BUSINESS', 'HEAD OFFICE', 'M', 'c.ozioko@infinitymfb.com', 'GABRIEL OLUDOTUN ADEWUNMI', null, null),
  (62, 'IMFB/20/0131', 'OWOLABI OLUBUNMI ADEBAMBO', 'CONFIRMED', 'COMPLIANCE OFFICER', 'RISK & COMPLIANCE', 'AGEGE & EGBEDA', 'F', 'o.owolabi@infinitymfb.com', 'BANKOLE TEMITOPE', 'ABIWON TOLULOPE', null),
  (63, 'IMFB/20/0135', 'ADEGUN FAVOUR IYANUOLUWA', 'CONFIRMED', 'ACCOUNTS OFFICER', 'FINANCIAL CONTROL', 'HEAD OFFICE', 'F', 'f.adegun@infinitymfb.com', 'AJAYI SAMUEL', 'OYELERE OLAYIDE', 'GABRIEL OLUDOTUN ADEWUNMI'),
  (64, 'IMFB/20/0137', 'JOHN SEMAWON ONI', 'CONFIRMED', 'BRANCH MANAGER', 'CREDIT & MARKETING', 'LAGOS ISLAND 1', 'M', 'j.oni@infinitymfb.com', 'OBIOHA ANNE', 'OLANAOKA OLANREWAJU YEMISI', null),
  (65, 'IMFB/20/0139', 'OLATEJU OLUFUNKE OLATUNBOSUN', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'IKORODU', 'F', 'o.olateju@infinitymgb.com', 'ODEPO SHOLA', 'OJABINENI MOSUN', 'OLANAOKA OLANREWAJU YEMISI'),
  (66, 'IMFB/20/0141', 'ABIODUN IDAYAT LAWAL', 'CONFIRMED', 'HR OFFICER', 'HUMAN RESOURCES', 'HEAD OFFICE', 'F', 'a.lawal@infinitymfb.com', 'OHAEGBU AWELE VICTORIA', 'GABRIEL OLUDOTUN ADEWUNMI', null),
  (67, 'IMFB/20/0145', 'CHIWENDU MINICENT CHINEDUM', 'CONFIRMED', 'SENIOR LOAN OFFICER', 'CREDIT & MARKETING', 'MUSHIN', 'F', 'c.chinedum@infinitymfb.com', 'ALONGE MARIAM', 'OBILOR IFEANYI', 'OLANAOKA OLANREWAJU YEMISI'),
  (68, 'IMFB/20/0147', 'SIMON TUNDE ADEMOLA', 'CONFIRMED', 'DRIVER', 'ADMINISTRATION', 'HEAD OFFICE', 'M', 'N/A', 'ORUSOSO  ISIOMA-NWALIGBE', 'OLANAOKA OLANREWAJU YEMISI', null),
  (69, 'IMFB/23/0305', 'AJILORE ODUNOLA  ESTHER', 'CONFIRMED', 'P.A. TO MD/CEO', 'ADMINISTRATION', 'HEAD OFFICE', 'F', 'e.ajilore@infinitymfb.com', 'GABRIEL OLUDOTUN ADEWUNMI', null, null),
  (70, 'IMFB/20/0147', 'OBASOYIN AYOKUNLE JOSEPH', 'CONFIRMED', 'COMPLIANCE OFFICER', 'RISK & COMPLIANCE', 'BARIGA/LAGOS Island 1', 'M', 'j.obasoyin@infinitymfb.com', 'BANKOLE TEMITOPE', 'ABIWON TOLULOPE', null),
  (71, 'IMFB/21/0148', 'AKOWE JACOB OREMIOSERIMHE', 'CONFIRMED', 'LEGAL OFFICER', 'LEGAL', 'HEAD OFFICE', 'M', 'j.akowe@infinitymfb.com', 'GABRIEL OLUDOTUN ADEWUNMI', null, null),
  (72, 'IMFB/21/0149', 'ISIOMA-NWALIGBE ORUSOSO', 'CONFIRMED', 'HEAD, ADMINISTRATION', 'ADMINISTRATION', 'HEAD OFFICE', 'F', 's.isioma@infinitymfb.com', 'GABRIEL OLUDOTUN ADEWUNMI', null, null),
  (73, 'IMFB/21/0153', 'ODEDINA YETUNDE MOTUNRAYO', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'BARIGA', 'F', 'y.odedina@infinitymfb.com', 'ATIKU HOPE', 'ADENLE ADEWALE OLUWAROTIMI', 'OLANAOKA OLANREWAJU YEMISI'),
  (74, 'IMFB/21/0157', 'ONYEMIBE GRACE CHINEDU', 'CONFIRMED', 'CUSTOMER SERVICE OFFICER', 'OPERATIONS', 'HEAD OFFICE', 'F', 'g.onyemibe@infinitymfb.com', 'UGUTE FEJIRO', null, null),
  (75, 'IMFB/21/0158', 'NNADILINWA LOVETH EBELE', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'ALABA', 'F', 'l.nnadinlinwa@infinitymfb.com', null, 'OBILOR IFEANYI', 'OLANAOKA OLANREWAJU YEMISI'),
  (76, 'IMFB/21/0160', 'JOSEPH REGINA MAXWELL', 'CONFIRMED', 'RISK OFFICER', 'RISK & COMPLIANCE', 'HEAD OFFICE', 'F', 'r.maxwell@infinitymfb.com', 'FATEYE KEHINDE', 'ABIWON TOLULOPE', null),
  (77, 'IMFB/21/0161', 'ADAMS ELIZABETH CHINYERE', 'CONFIRMED', 'SENIOR LOAN OFFICER', 'CREDIT & MARKETING', 'LAGOS ISLAND 1', 'F', 'e.adams@infinitymfb.com', 'ONI JOHN', 'OBIOHA ANNE', 'OLANAOKA OLANREWAJU YEMISI'),
  (78, 'IMFB/21/0179', 'ONWUKA OLUCHI JUSTINA', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'OSHODI', 'F', 'o.onwuka@infinitymfb.com', 'ENYINNAYA GLORIA IHUOMA', 'OBILOR IFEANYI', 'OLANAOKA OLANREWAJU YEMISI'),
  (79, 'IMFB/22/0189', 'OFORNAKARA CHARITY CHIMEREM', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'YABA', 'F', 'c.ofornarara@infinitymfb.com', 'OLUFUNWA MARY', 'OBILOR IFEANYI', 'OLANAOKA OLANREWAJU YEMISI'),
  (80, 'IMFB/22/0190', 'NWAFOR JULIET CHIJINDU', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'OSHODI', 'F', 'j.nwafor@infinitymfb.com', 'ENYINNAYA GLORIA IHUOMA', 'OBILOR IFEANYI', 'OLANAOKA OLANREWAJU YEMISI'),
  (81, 'IMFB/22/0200', 'SANNI ABIODUN AMINAT', 'CONFIRMED', 'OFFICE ASSISTANT', 'ADMINISTRATION', 'OWODE', 'F', 'N/A', 'OLASANJO TOYIN', 'ORUSOSO  ISIOMA-NWALIGBE', null),
  (82, 'IMFB/22/0201', 'OMOLE TINAPETER', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'ALABA', 'F', 't.peters@infinitymfb.com', null, 'OBILOR IFEANYI', 'OLANAOKA OLANREWAJU YEMISI'),
  (83, 'IMFB/22/0206', 'OKEDIJI OLASUNKANMI PELUMI', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'MUSHIN', 'F', 'o.okediji@infinitymfb.com', 'ALONGE MARIAM', 'OBILOR IFEANYI', 'OLANAOKA OLANREWAJU YEMISI'),
  (84, 'IMFB/22/0209', 'IJIE CONSCIENCE EMESI', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'EGBEDA', 'F', 'c.ijie@infinitymfb.com', null, 'EUNICE MANKANJUOLA', 'OLANAOKA OLANREWAJU YEMISI'),
  (85, 'IMFB/22/0221', 'OJO TEMITOPE', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'AGEGE', 'F', 't.ojo@infinitymfb.com', 'ADINOGE ESTHER', 'ADENLE ADEWALE OLUWAROTIMI', 'OLANAOKA OLANREWAJU YEMISI'),
  (86, 'IMFB/22/0218', 'IGWILO VIVIAN CHIKA', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'IBEJU-LEKKI', 'F', 'v.igwilo@infinitymfb.com', null, 'OBIOHA ANNE', 'OLANAOKA OLANREWAJU YEMISI'),
  (87, 'IMFB/22/0229', 'OLOWU OLADIPUPO RASAQ', 'CONFIRMED', 'COMPLIANCE OFFICER', 'RISK & COMPLIANCE', 'TRADE FAIR/BOUNDARY/ALABA', 'M', 'o.olowu@infinitymfb.com', 'BANKOLE TEMITOPE', 'ABIWON TOLULOPE', null),
  (88, 'IMFB/22/0231', 'AZEEZ KAFAYAT DOLAPO', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'OWODE', 'F', 'k.azeez@infinitymfb.com', 'OLASANJO TOYIN', 'OJABINENI MOSUN', 'OLANAOKA OLANREWAJU YEMISI'),
  (89, 'IMFB/22/0236', 'UNWANA MARIA PROMISE', 'CONFIRMED', 'OFFICE ASSISTANT', 'ADMINISTRATION', 'MUSHIN', 'F', 'N/A', 'ALONGE MARIAM', 'ORUSOSO  ISIOMA-NWALIGBE', null),
  (90, 'IMFB/22/0241', 'OJO OLUWADAPO AYOTUNDE', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'LAGOS ISLAND 1', 'M', 'o.ojo@infinitymfb.com', 'ONI JOHN', 'OBIOHA ANNE', 'OLANAOKA OLANREWAJU YEMISI'),
  (91, 'IMFB/22/0243', 'IKONOH PATRICIA ALPHONSUS', 'CONFIRMED', 'ASSISTANT STRATEGY & RESEARCH MANAGER', 'RESEARCH & STRATEGY', 'HEAD OFFICE', 'F', 'p.ikonoh@infinitymfb.com', 'GABRIEL OLUDOTUN ADEWUNMI', null, null),
  (92, 'IMFB/22/0247', 'OYEYEMI SAMSON OLATUNJI', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'HEAD OFFICE', 'M', 's.oyeyemi@infinitymfb.com', 'ONUMAJULU VICTOR', 'ADENLE ADEWALE OLUWAROTIMI', 'OLANAOKA OLANREWAJU YEMISI'),
  (93, 'IMFB/22/0250', 'ADEKUNLE ADENIKE VICTORIA', 'CONFIRMED', 'UNIT HEAD, TRAINING', 'HUMAN RESOURCES', 'HEAD OFFICE', 'F', 'a.adekunle@infinitymfb.com', 'OHAEGBU AWELE VICTORIA', 'GABRIEL OLUDOTUN ADEWUNMI', null),
  (94, 'IMFB/22/0251', 'BAMIGBOYE MARGARET ANDRE', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'BOUNDARY', 'F', 'm.andre@infinitymfb.com', 'ADENIRAN HAMMED', 'OBIOHA ANNE', 'OLANAOKA OLANREWAJU YEMISI'),
  (95, 'IMFB/22/0257', 'NWOYE NJIDEKA RACHEAL', 'CONFIRMED', 'OPERATIONS OFFICER', 'OPERATIONS', 'ALABA', 'F', 'n.nwoye@infinitymfb.com', 'UGUTE FEJIRO', null, null),
  (96, 'IMFB/22/0261', 'EKE ROSE HANNAH', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'ODOGUNYAN', 'F', 'r.eke@infinitymfb.com', 'OGUNFOWORA OMOTAYO', 'OJABINENI MOSUN', 'OLANAOKA OLANREWAJU YEMISI'),
  (97, 'IMFB/22/0262', 'OYEBAMIJI OMOTAYO ADEBOLA', 'CONFIRMED', 'COMPLIANCE OFFICER', 'RISK & COMPLIANCE', 'KETU & HEAD OFFICE', 'F', 'o.oyebamiji@infinitymfb.com', 'BANKOLE TEMITOPE', 'ABIWON TOLULOPE', null),
  (98, 'IMFB/22/0263', 'DARE IBRAHIM SHOLA', 'CONFIRMED', 'WHOLESALE LENDING EXECUTIVE', 'CREDIT & MARKETING', 'LAGOS ISLAND 2', 'M', 'i.dare@infinitymfb.com', 'OLAYEMI ODUNOLA', 'AJISEGBEDE GBEMI', null),
  (99, 'IMFB/22/0268', 'ISHADARE FEMI ISRAEL', 'CONFIRMED', 'COMPLIANCE OFFICER', 'RISK & COMPLIANCE', 'MUSHIN/YABA', 'M', 'f.ishadare@infinitymfb.com', 'BANKOLE TEMITOPE', 'ABIWON TOLULOPE', null),
  (100, 'IMFB/22/0273', 'SOTIMEHIN MARY OMOTAYO', 'CONFIRMED', 'OFFICE ASSISTANT', 'ADMINISTRATION', 'YABA 2', 'F', 'N/A', 'OLUFUNWA MARY', 'ORUSOSO  ISIOMA-NWALIGBE', null),
  (101, 'IMFB/23/0277', 'FASIKU DAVID ADEOYE', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'BOUNDARY', 'M', 'd.fasiku@infinitymfb.com', 'ADENIRAN HAMMED', 'OBIOHA ANNE', 'OLANAOKA OLANREWAJU YEMISI'),
  (102, 'IMFB/23/0281', 'OLUWATOSIN  OLUFUNWA MARY', 'CONFIRMED', 'BRANCH MANAGER', 'CREDIT & MARKETING', 'SABO/YABA', 'F', 'm.olufunwa@infinitymfb.com', 'OBIOHA ANNE', 'OLANAOKA OLANREWAJU YEMISI', null),
  (103, 'IMFB/23/0294', 'HARUNA HASSANAT FAVOUR', 'CONFIRMED', 'OPERATIONS OFFICER', 'OPERATIONS', 'KOLA', 'F', 'f.haruna@infinitymfb.com', 'UGUTE FEJIRO', null, null),
  (104, 'IMFB/23/0296', 'AJIBIKE ARAFAT MORENIKE', 'CONFIRMED', 'OFFICE ASSISTANT', 'ADMINISTRATION', 'LAGOS ISLAND 2', 'F', null, 'OLAYEMI ODUNOLA', 'ORUSOSO  ISIOMA-NWALIGBE', null),
  (105, 'IMFB/23/0298', 'QUADRI OSENAT IYABO', 'CONFIRMED', 'OFFICE ASSISTANT', 'ADMINISTRATION', 'ILE-EPO', 'F', null, 'AGUKWE PECULIAR', 'ORUSOSO  ISIOMA-NWALIGBE', null),
  (106, 'IMFB/23/0300', 'ADEGUNWA EGENA GRACE', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'IKORODU', 'F', 'e.adegunwa@infinitymfb.com', 'OLANASE GRACE', 'OJABINENI MOSUN', 'GABRIEL OLUDOTUN ADEWUNMI'),
  (107, 'IMFB/23/0301', 'ADELEYE (ANIMASAHUN) ABIMBOLA LANIKE', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'KOLA', 'F', 'a.adeleye@infinitymfb.com', 'ADEKEYE ADELEKE EMMANUEL', 'OJABINENI MOSUN', 'OLANAOKA OLANREWAJU YEMISI'),
  (108, 'IMFB/23/0304', 'OGILODO PROMISE', 'CONFIRMED', 'OFFICE ASSISTANT', 'ADMINISTRATION', 'KETU', 'M', 'N/A', 'DISU HANNAH', 'ORUSOSO  ISIOMA-NWALIGBE', null),
  (109, 'IMFB/23/0305', 'ANOCHILI FAVOUR ADANNA', 'CONFIRMED', 'OFFICE ASSISTANT', 'ADMINISTRATION', 'ALABA', 'F', 'N/A', null, 'ORUSOSO  ISIOMA-NWALIGBE', null),
  (110, 'IMFB/23/0311', 'YUSUF DEBORAH TEMITOPE', 'CONFIRMED', 'CPC EDGE OFFICER', 'E-BUSINESS', 'HEAD OFFICE', 'F', 'd.yusuf@infinitymfb.com', 'OZIOKO COSMOS', null, null),
  (111, 'IMFB/23/0312', 'JUMOKE  KAUSARAT', 'CONFIRMED', 'OFFICE ASSISTANT', 'ADMINISTRATION', 'BOUNDARY', 'F', 'N/A', 'ADENIRAN HAMMED', 'OBIOHA ANNE', 'ORUSOSO  ISIOMA-NWALIGBE'),
  (112, 'IMFB/23/0314', 'SALIU OLUWASEUN JOHN SALIU', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'IKORODU', 'M', 's.oluwaseun@infinitymfb.com', 'ODEPO SHOLA', 'OJABINENI MOSUN', 'OLANAOKA OLANREWAJU YEMISI'),
  (113, 'IMFB/23/0336', 'ALEBIOSU IYEWUNMI REBECCA', 'CONFIRMED', 'OFFICE ASSISTANT', 'ADMINISTRATION', 'OSHODI', 'F', null, 'ENYINNAYA GLORIA IHUOMA', 'ORUSOSO  ISIOMA-NWALIGBE', null),
  (114, 'IMFB/23/0337', 'BELLO BALIKIS ABIOLA', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'IKORODU', 'F', 'b.bello@infinitymfb.com', 'OLANASE GRACE', 'OJABINENI MOSUN', 'OLANAOKA OLANREWAJU YEMISI'),
  (115, 'IMFB/23/0345', 'ADEWOYE TEMITOPE DEBORAH', 'CONFIRMED', 'CUSTOMER SERVICE OFFICER', 'OPERATIONS', 'MUSHIN', 'F', 't.adewoye@infinitymfb.com', 'UGUTE FEJIRO', null, null),
  (116, 'IMFB/24/0351', 'OLAREWAJU OLUWATOSIN JULIANA', 'CONFIRMED', 'TELLER', 'OPERATIONS', 'KETU', 'F', 'o.olarewaju@infinitymfb.com', 'UGUTE FEJIRO', null, null),
  (117, 'IMFB/21/0175', 'OBASUYI OLUWATOBI SAMSON', 'CONFIRMED', 'CSO', 'OPERATIONS', 'AJAH', 'M', 's.obasuyi@infinitymfb.com', 'UGUTE FEJIRO', null, null),
  (118, 'IMFB/24/0035', 'ECHEBIRI EGO JOY', 'CONFIRMED', 'PAYDAY LOAN OFFICER', 'CREDIT & MARKETING', 'HEAD OFFICE', 'F', 'e.echebiri@infinitymfb.com,', null, null, null),
  (119, 'IMFB/24/0032', 'JOHNSON RACHEAL BLESSING', 'CONFIRMED', 'OFFICE ASSISTANT', 'ADMINISTRATION', 'IKORODU', 'F', 'N/A', 'ODEPO SHOLA', 'ORUSOSO  ISIOMA-NWALIGBE', null),
  (120, 'IMFB/24/0357', 'AGWINEDE JUDITH OTASOWIE', 'CONFIRMED', 'SENIOR LOAN OFFICER', 'CREDIT & MARKETING', 'EGBEDA', 'F', 'j.agwinede@infinitymfb.com', null, 'ADENLE ADEWALE OLUWAROTIMI', 'OLANAOKA OLANREWAJU YEMISI'),
  (121, 'IMFB/24/0359', 'KILANI FUNMILAYO SEUN', 'CONFIRMED', 'P A TO BOD', 'ADMINISTRATION', 'HEAD OFFICE', 'F', 'f.kilani@infinitymfb.com', 'UMUKORO KELECH', 'BOD', null),
  (122, 'IMFB/24/0361', 'ETIM EDIKAN EFFIONG', 'CONFIRMED', 'SENIOR LOAN OFFICER', 'CREDIT & MARKETING', 'IBEJU-LEKKI', 'M', 'e.edikan@infinitymfb.com', null, 'OBIOHA ANNE', 'OLANAOKA OLANREWAJU YEMISI'),
  (123, 'IMFB/24/0362', 'ADEGBENRO ADEYINKA GANIYAT', 'CONFIRMED', 'FUND TRANSFER OFFICER', 'OPERATIONS', 'HEAD OFFICE', 'F', 'a.adegbenro@infinitymfb.com', 'UGUTE FEJIRO', null, null),
  (124, 'IMFB/24/0365', 'FATUNWASE ABIODUN EBENEZER', 'CONFIRMED', 'HR BUSINESS PARTNER', 'HUMAN RESOURCES', 'HEAD OFFICE', 'M', 'a.fatunwase@infinitymfb.com', 'OHAEGBU AWELE VICTORIA', 'GABRIEL OLUDOTUN ADEWUNMI', null),
  (125, 'IMFB/24/0367', 'LAWRENCE FUNMILAYO IYANUOLUWA', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'LAGOS ISLAND 1', 'F', 'f.lawrence@infinitymfb.com', 'ONI JOHN', 'OBIOHA ANNE', 'OLANAOKA OLANREWAJU YEMISI'),
  (126, 'IMFB/24/0368', 'IFESANWO OLUWAFUNMILAYO TEMITOPE', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'OSHODI', 'F', 'f.ifesanwo@infinitymfb.com', 'ENYINNAYA GLORIA IHUOMA', 'OBILOR IFEANYI', 'OLANAOKA OLANREWAJU YEMISI'),
  (127, 'IMFB/24/0378', 'ADEYEMI OLAMILEKAN OLUWASESAN', 'CONFIRMED', 'COMPLIANCE OFFICER', 'RISK & COMPLIANCE', 'KOLA & ILE-EPO', 'M', 'o.adeyemi@infinitymfb.com', 'BANKOLE TEMITOPE', 'ABIWON TOLULOPE', null),
  (128, 'IMFB/24/0379', 'ADEBAYO ABAYOMI', 'CONFIRMED', 'BRANCH MANAGER', 'CREDIT & MARKETING', 'AJAH', 'M', 'a.adebayo@infinitymfb.com', 'OBIOHA ANNE', 'OLANAOKA OLANREWAJU YEMISI', null),
  (129, 'IMFB/24/0382', 'OKUNLOLA DAMILOLA ALILAT', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'BARIGA', 'F', 'd.okunlola@infinitymfb.com', 'ATIKU HOPE', 'ADENLE ADEWALE OLUWAROTIMI', 'OLANAOKA OLANREWAJU YEMISI'),
  (130, 'IMFB/24/0383', 'AGHANENU NKECHI ELIZABETH', 'CONFIRMED', 'ACCOUNTS OFFICER', 'FINANCIAL CONTROL', 'HEAD OFFICE', 'F', 'n.aghanenu@infinitymfb.com', 'AJAYI SAMUEL', 'OYELERE OLAYIDE', 'GABRIEL OLUDOTUN ADEWUNMI'),
  (131, 'IMFB/24/0384', 'UGUTE EVELYN OGHENEFEJIRO', 'CONFIRMED', 'HEAD OF OPERATION', 'OPERATIONS', 'HEAD OFFICE', 'F', 'e.ugute@infinitymfb.com', 'GABRIEL OLUDOTUN ADEWUNMI', null, null),
  (132, 'IMFB/24/0386', 'HASSAN BOLANLE MONSURAT', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'KETU', 'F', 'b.hassan@infinitymfb.com', 'DISU HANNAH', 'ADENLE ADEWALE OLUWAROTIMI', 'OLANAOKA OLANREWAJU YEMISI'),
  (133, 'IMFB/24/0349', 'JOLOMI OLUWASEYI ISAAC', 'CONFIRMED', 'SENIOR LOAN OFFICER (TEAM LEAD)', 'CREDIT & MARKETING', 'TRADE FAIR', 'M', 'o.jolomi@infinitymfb.com', 'OBILOR IFEANYIN', 'OLANAOKA OLANREWAJU YEMISI', null),
  (134, 'IMFB/24/0390', 'QUADRI MURITALA ABIODUN', 'CONFIRMED', 'SENIOR LOAN OFFICER', 'CREDIT & MARKETING', 'OWODE', 'M', 'm.quadri@infinitymfb.com', 'OLASANJO TOYIN', 'OJABINENI MOSUN', 'OLANAOKA OLANREWAJU YEMISI'),
  (135, 'IMFB/24/0391', 'TAIWO ADEOLA TITILOPE', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'EGBEDA', 'f', 'a.taiwo@infinitymfb.com', null, 'ADENLE ADEWALE OLUWAROTIMI', 'OLANAOKA OLANREWAJU YEMISI'),
  (136, 'IMFB/24/0392', 'BAKARE OPEYEMI IBUKUNOLUWA', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'OWODE', 'F', 'o.bakare@infinitymfb.com', 'OLASANJO TOYIN', 'OJABINENI MOSUN', 'OLANAOKA OLANREWAJU YEMISI'),
  (137, 'IMFB/24/0396', 'AROKODARE TEJUMOLA REBECCA', 'CONFIRMED', 'OFFICE ASSISTANT', 'ADMINISTRATION', 'ODOGUNYAN', 'F', 'N/A', 'OGUNFOWORA OMOTAYO', 'ORUSOSO  ISIOMA-NWALIGBE', null),
  (138, 'IMFB/24/0395', 'AKANDE BABAJIDE JOHN', 'CONFIRMED', 'TREASURY MANAGER', 'CREDIT & MARKETING', 'HEAD OFFICE', 'M', 'b.akande@infinitymfb.com', 'GABRIEL OLUDOTUN ADEWUNMI', null, null),
  (139, 'IMFB/24/0397', 'MORJI JOY MILDRED', 'CONFIRMED', 'OFFICE ASSISTANT', 'ADMINISTRATION', 'IBEJU-LEKKI', 'F', 'N/A', null, 'ORUSOSO  ISIOMA-NWALIGBE', null),
  (140, 'IMFB/24/0404', 'KOLAWOLE TEMITOPE SHERIFAT', 'CONFIRMED', 'TELLER', 'OPERATIONS', 'HEAD OFFICE', 'F', 't.kolawole@infinitymfb.com', 'UGUTE FEJIRO', null, null),
  (141, 'IMFB/24/0405', 'OWANEYE TOBILOBA ELIZABETH', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'ODOGUNYAN', 'F', 't.owaneye@infinitymfb.com', 'OGUNFOWORA OMOTAYO', 'OJABINENI MOSUN', 'OLANAOKA OLANREWAJU YEMISI'),
  (142, 'IMFB/24/0408', 'ANYEBE GABRIEL', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'AJAH', 'M', 'g.anyebe@infinitymfb.com', 'ADEBAYO ABOYOMI', 'OBIOHA ANNE', 'OLANAOKA OLANREWAJU YEMISI'),
  (143, 'IMFB/24/0409', 'ENYINNAYA IHUOMA GLORIA', 'CONFIRMED', 'BRANCH MANAGER', 'CREDIT & MARKETING', 'OSHODI', 'F', 'i.enyinnaya@infinitymfb.com', 'OBILOR IFEANYIN', 'OLANAOKA OLANREWAJU YEMISI', null),
  (144, 'IMFB/24/0410', 'AFOLABI TEMITOPE GRACE', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'AGEGE', 'F', 't.afolabi@infinitymfb.com', 'ADINOGE ESTHER', 'ADENLE ADEWALE OLUWAROTIMI', 'OLANAOKA OLANREWAJU YEMISI'),
  (145, 'IMFB/24/0411', 'OLADIPUPO ABIDEMI MODINAT', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'IKEJA', 'f', 'a.oladipupo@infinitymfb.com', 'REXONA OKODUA', 'OBILOR IFEANYI', 'OLANAOKA OLANREWAJU YEMISI'),
  (146, 'IMFB/24/0406', 'OGUNDIYAN TOLULOPE DAVID', 'CONFIRMED', 'WHOLESALE LENDING EXECUTIVE', 'CREDIT & MARKETING', 'HEAD OFFICE', 'M', 't.ogundiyan@infinitymfb.com', 'AJISEGBEDE GBEMI', null, null),
  (147, 'IMFB/25/0413', 'EZEANI JANE CHIAMAKA', 'CONFIRMED', 'TELLER', 'OPERATIONS', 'HEAD OFFICE', 'F', 'j.ezeani@infinitymfb.com', 'UGUTE FEJIRO', null, null),
  (148, 'IMFB/25/0419', 'ODESANYA ADESOLA MORIAMO', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'IKORODU', 'F', 'a.odesanya@infinitymfb.com', 'OLANASE GRACE', 'OJABINENI MOSUN', 'OLANAOKA OLANREWAJU YEMISI'),
  (149, 'IMFB/25/0420', 'OLADIPUPO AZEEZAT KOFOWOROLA', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'OWODE', 'F', 'k.oladipupo@infinitymfb.com', 'OLASANJO TOYIN', 'OJABINENI MOSUN', 'OLANAOKA OLANREWAJU YEMISI'),
  (150, 'IMFB/25/0421', 'EKEVWE EMOGHENE GRACE', 'CONFIRMED', 'RISK OFFICER', 'RISK & COMPLIANCE', 'HEAD OFFICE', 'F', 'e.ekevwe@infinitymfb.com', 'FATEYE KEHINDE', 'ABIWON TOLULOPE', null),
  (151, 'IMFB/25/0422', 'OKENWA CHIAMAKA JULIET', 'CONFIRMED', 'OPERATIONS OFFICER', 'OPERATIONS', 'LAGOS ISLAND 2', 'F', 'c.okenwa@infinitymfb.com', 'UGUTE FEJIRO', null, null),
  (152, 'IMFB/25/0423', 'OKEH FEJIRO NANCY', 'CONFIRMED', 'RECOVER OFFICER (CALL MONITORING)', 'RECOVERY', 'HEAD OFFICE', 'F', 'f.okeh@infinitymfb.com', 'ABIWON TOLULOPE', 'GABRIEL OLUDOTUN ADEWUNMI', null),
  (153, 'IMFB/25/0426', 'ADEDEJI TAWAKALITU ABOSEDE', 'CONFIRMED', 'OFFICE ASSISTANT', 'ADMINISTRATION', 'AJAH', 'F', 'N/A', 'ABAYOMI ADEBAYO', 'ORUSOSO  ISIOMA-NWALIGBE', null),
  (154, 'IMFB/25/0427', 'TIAMIYU ARAMIDE BASIRAT', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'KETU', 'F', 'a.tiamiyu@infinitymfb.com', 'DISU HANNAH', 'ADENLE ADEWALE OLUWAROTIMI', 'OLANAOKA OLANREWAJU YEMISI'),
  (155, 'IMFB/25/0428', 'KUJIMIYO DAVID ABAYOMI', 'CONFIRMED', 'E-BUSINESS OFFICER', 'E-BUSINESS', 'HEAD OFFICE', 'M', 'd.kujimiyo@infinitymfb.com', 'OZIOKO COSMOS', 'GABRIEL OLUDOTUN ADEWUNMI', null),
  (156, 'IMFB/25/0431', 'NZEKWE FRANCIS EJIKE', 'CONFIRMED', 'BDM', 'CREDIT & MARKETING', 'KETU', 'M', 'f.nzekwe@infinitymfb.com', 'DISU HANNAH', 'ADENLE ADEWALE OLUWAROTIMI', 'OLANAOKA OLANREWAJU YEMISI'),
  (157, 'IMFB/25/0434', 'BALA GRACIOUS IJINUE', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'BOUNDARY', 'F', 'g.bala@infinitymfb.com', 'ADENIRAN HAMMED', 'OBIOHA ANNE', 'OLANAOKA OLANREWAJU YEMISI'),
  (158, 'IMFB/25/0438', 'DIKE VERA AMARACHI', 'CONFIRMED', 'CUSTOMER SERVICE OFFICER', 'OPERATIONS', 'HEAD OFFICE', 'F', 'V.DIKE@INFINITY', 'UGUTE FEJIRO', null, null),
  (159, 'IMFB/25/0443', 'ONUMAJULU VICTOR EMENIKE', 'CONFIRMED', 'BRANCH MANAGER', 'CREDIT & MARKETING', 'HEAD OFFICE', 'M', 'v.onumajulu@infinitymfb.com', 'ADENLE ADEWALE OLUWAROTIMI', 'OLANAOKA OLANREWAJU YEMISI', null),
  (160, 'IMFB/25/0448', 'ASHAOLU OLUWATOSIN ROSELINE', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'ODOGUNYAN', 'F', 'o.ashaolu@infinitymfb.com', 'OGUNFOWORA OMOTAYO', 'OJABINENI MOSUN', 'OLANAOKA OLANREWAJU YEMISI'),
  (161, 'IMFB/25/0449', 'ODOFIN ADEOLA IYANUOLUWA', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'IKORODU', 'F', 'a.odofin@infinitymfb.com', 'ODEPO SHOLA', 'OJABINENI MOSUN', 'OLANAOKA OLANREWAJU YEMISI'),
  (162, 'IMFB/25/0451', 'AYOBANDELE ADEOLA  OLUWASEUN', 'CONFIRMED', 'RECOVERY OFFICER', 'RISK & COMPLIANCE', 'KETU', 'M', 'a.ayobandele@infinitymfb.com', 'ABIWON TOLULOPE', null, null),
  (163, 'IMFB/25/0455', 'AJANI OLUSOLA OLADEJI', 'CONFIRMED', 'WHOLESALE LENDING EXECUTIVE', 'CREDIT & MARKETING', 'LAGOS ISLAND2', 'M', 'o.ajani@infinitymfb.com', 'OLAYEMI ODUNOLA', 'AJISEGBEDE GBEMI', null),
  (164, 'IMFB/25/0458', 'ELEMUE JOY OMAMUZO', 'UNCONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'BOUNDARY', 'F', 'j.elemue@infinitymfb.com', 'ADENIRAN HAMMED', 'OBIOHA ANNE', 'OLANAOKA OLANREWAJU YEMISI'),
  (165, 'IMFB/25/0459', 'OTUKOKO BLESSING OKIKIOLA', 'CONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'AJAH', 'F', 'b.otukoko@infinitymfb.com', 'ABAYOMI ADEBAYO', 'OBIOHA ANNE', 'OLANAOKA OLANREWAJU YEMISI'),
  (166, 'IMFB/25/0460', 'OYELERE OLAYIDE AKANJI', 'CONFIRMED', 'HEAD, FINCON', 'FINANCIAL CONTROL', 'HEAD OFFICE', 'M', 'o.oyelere@infinitymfb.com', 'GABRIEL OLUDOTUN ADEWUNMI', null, null),
  (167, 'IMFB/25/0461', 'ADEWOLE OMONIYI PHILIP', 'CONFIRMED', 'LOAN ADMIN OFFICER', 'RISK & COMPLIANCE', 'HEAD OFFICE', 'M', 'p.adewole@infinitymfb.com', 'AYOLADE MOYINOLUWA', 'ABIWON TOLULOPE', null),
  (168, 'IMFB/25/0463', 'ALAYANDE OLUWASEGUN AYOMIDE', 'CONTRACT STAFF', 'DRIVER', 'ADMINISTRATION', 'HEAD OFFICE', 'M', 'N/A', 'AJISEGBEDE GBEMI', 'ORUSOSO  ISIOMA-NWALIGBE', null),
  (169, 'IMFB/25/0464', 'EBADE REMI', 'CONFIRMED', 'DRIVER', 'ADMINISTRATION', 'HEAD OFFICE', 'M', 'N/A', 'OLANAOKA OLANREWAJU YEMISI', 'ORUSOSO  ISIOMA-NWALIGBE', null),
  (170, 'IMFB/26/0465', 'SOSSA ABIODUN CHRISTIANA', 'CONFIRMED', 'OFFICE ASSISTANT', 'ADMINISTRATION', 'BARIGA', 'F', 'N/A', 'ATIKU HOPE', 'ORUSOSO  ISIOMA-NWALIGBE', null),
  (171, 'IMFB/26/0466', 'TEMITOPE BASHIRU ZAINAB', 'CONFIRMED', 'OFFICE ASSISTANT', 'ADMINISTRATION', 'IKEJA', 'F', 'N/A', 'OKODUA REXONA', 'ORUSOSO  ISIOMA-NWALIGBE', null),
  (172, 'IMFB/26/0467', 'ODUMADE SIKEMI BOLANLE', 'UNCONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'EGBEDA', 'F', 's.odumade@infinitymfb', null, 'ADENLE ADEWALE OLUWAROTIMI', 'OLANAOKA OLANREWAJU YEMISI'),
  (173, 'IMFB/26/0468', 'DADA SEUNFUNMI ISREAL', 'UNCONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'KETU', 'M', 's.dada@infinitymfb.com', 'DISU HANNAH', 'ADENLE ADEWALE OLUWAROTIMI', 'OLANAOKA OLANREWAJU YEMISI'),
  (174, 'IMFB/26/0469', 'OHAEGBU AWELE VICTORIA', 'UNCONFIRMED', 'HEAD, HUMAN RESOURCES', 'HUMAN RESOURCES', 'HEAD OFFICE', 'F', 'a.ohaegbu@infinitymfb.com', 'GABRIEL OLUDOTUN ADEWUNMI', null, null),
  (175, 'IMFB/26/0470', 'OKWUTE MARY AJUMAH', 'UNCONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'BARIGA', 'F', 'm.ajumah@infinitymfb.com', 'ATIKU HOPE', 'ADENLE ADEWALE OLUWAROTIMI', 'OLANAOKA OLANREWAJU YEMISI'),
  (176, 'IMFB/26/0471', 'OLADELE OLUWAKEMI BLESSING', 'CONFIRMED', 'CUSTOMER SERVICE OFFICER', 'OPERATIONS', 'EGBEDA', 'F', 'o.oladele@infinitymfb.com', 'UGUTE FEJIRO', null, null),
  (177, 'IMFB/26/0473', 'OSUNTILE TOBI SANYAOLU', 'UNCONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'IKORODU', 'M', 't.osuntile@infinitymfb.com', 'OLANASE GRACE', 'OJABINENI MOSUN', 'OLANAOKA OLANREWAJU YEMISI'),
  (178, 'IMFB/26/0478', 'ODEDIMEJI AMINAT TUNRAYO', 'UNCONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'SABO/YABA', 'F', 'a.odedimeji@infinitymfb.com', 'OLUFUNWA MARY', 'OBIOHA ANNE', 'OLANAOKA OLANREWAJU YEMISI'),
  (179, 'IMFB/26/0479', 'BELLO FATIMOT LARA', 'UNCONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'HEAD OFFICE', 'F', 'f.bello@infinitymfb.com', 'ONUMAJULU VICTOR', 'ADENLE ADEWALE OLUWAROTIMI', 'OLANAOKA OLANREWAJU YEMISI'),
  (180, 'IMFB/26/0487', 'ADEWUMI OLUWATOMISIN DEBORAH', 'UNCONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'AJAH', 'F', 'o.adewumi@infinitymfb.com', 'ABAYOMI ADEBAYO', 'OBIOHA ANNE', 'OLANAOKA OLANREWAJU YEMISI'),
  (181, 'IMFB/26/0488', 'MEMUDU-ADAMS ADENIKE ADIJAT', 'UNCONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'EGBEDA', 'F', 'a.adams-memud@infinitymfb.com', null, 'ADENLE ADEWALE OLUWAROTIMI', 'OLANAOKA OLANREWAJU YEMISI'),
  (182, 'IMFB/26/0491', 'AMUCHI GIFT', 'UNCONFIRMED', 'RECEPTIONIST', 'ADMINISTRATION', 'HEAD OFFICE', 'F', 'g.amuchi@infinitymfb.com', 'UMUKORO KELECH', null, null),
  (183, 'IMFB/26/0489', 'ADEBAYO OLUWATOSIN SARAH', 'UNCONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'IKORODU', 'F', 'o.adebayo@infinitymfb.com', 'ODEPO SHOLA', 'OJABINENI MOSUN', 'OLANAOKA OLANREWAJU YEMISI'),
  (184, 'IMFB/26/0490', 'FIDELIS IFEANYI DAVID', 'UNCONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'ILE-EPO', 'M', 'i.fidelis@infinitymfb.com', 'AGUKWE PECULIAR', 'OJABINENI MOSUN', 'OLANAOKA OLANREWAJU YEMISI'),
  (185, 'IMFB/26/0494', 'FAKUNLE FLORENCE OLAIDE', 'UNCONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'IKEJA', 'F', 'f.fakunle@infinitymfb.com', 'REXONA OKODUA', 'OBILOR IFEANYI', 'OLANAOKA OLANREWAJU YEMISI'),
  (186, 'IMFB/26/0495', 'UKA AUGUSTA CHIWENDU', 'UNCONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'IKORODU', 'F', 'a.uka@infinitymfb.com', 'ODEPO SHOLA', 'OJABINENI MOSUN', 'OLANAOKA OLANREWAJU YEMISI'),
  (187, 'IMFB/26/0496', 'AKPAN BLESSING EDIDIONG', 'UNCONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'SABO/YABA', 'F', 'b.akpan@infinitymfb.com', 'OLUFUNWA MARY', 'OBIOHA ANNE', 'OLANAOKA OLANREWAJU YEMISI'),
  (188, 'IMFB/26/0497', 'BALOGUN DABIRA ITEOLUWAKISHI', 'UNCONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'KOLA', 'F', 'd.dabira@infinitymfb.com', 'ADEKEYE ADELEKE EMMANUEL', 'OJABINENI MOSUN', 'OLANAOKA OLANREWAJU YEMISI'),
  (189, 'IMFB/26/0498', 'ADENIRAN HAMMED BOLAJI', 'UNCONFIRMED', 'BRANCH MANAGER', 'CREDIT & MARKETING', 'BOUNDARY', 'M', 'h.adeniran@infinitymfb.com', 'OBIOHA ANNE', 'OLANAOKA OLANREWAJU YEMISI', null),
  (190, 'IMFB/26/0499', 'AKINLEYE OLUWASOPE DORCAS', 'UNCONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'BARIGA', 'F', 'o.akinleye@infinitymfb.com', 'ATIKU HOPE', 'ADENLE ADEWALE OLUWAROTIMI', 'OLANAOKA OLANREWAJU YEMISI'),
  (191, 'IMFB/26/0501', 'YAMAH ABDULATEEF', 'UNCONFIRMED', 'WHOLESALE LENDING EXECUTIVE', 'CREDIT & MARKETING', 'HEAD OFFICE', 'M', 'a.yamah@infinitymfb.com', 'AJISEGBEDE GBEMI', null, null),
  (192, 'IMFB/26/0504', 'AGUKWE PECULIAR IFEOMA', 'UNCONFIRMED', 'BRANCH MANAGER TEAM 2', 'CREDIT & MARKETING', 'ILE-EPO', 'F', 'p.agukwe@infinitymfb.com', 'OJABINENI MOSUN', 'OLANAOKA OLANREWAJU YEMISI', null),
  (193, 'IMFB/26/0506', 'ANENE IFEYINWA CHINWOKE', 'UNCONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'ALABA', 'F', 'i.anene@infinitymfb.com', null, 'OBILOR IFEANYI', 'OLANAOKA OLANREWAJU YEMISI'),
  (194, 'IMFB/26/0507', 'AKINLOYE ADEBAYO', 'UNCONFIRMED', 'BDM', 'CREDIT & MARKETING', 'KOLA', 'M', 'o.akinloye@infinitymfb.com', 'ADEKEYE ADELEKE EMMANUEL', 'OLANAOKA OLANREWAJU YEMISI', null),
  (195, 'IMFB/26/0508', 'SHITTU ABIODUN YUSUF', 'UNCONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'KOLA', 'M', 'a.shittu@infinitymfb.com', 'ADEKEYE ADELEKE EMMANUEL', 'OJABINENI MOSUN', 'OLANAOKA OLANREWAJU YEMISI'),
  (196, 'IMFB/26/0509', 'JIMOH HELEN TOLA', 'UNCONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'IBEJU-LEKKI', 'F', 'h.jimoh@infinitymfb.com', null, 'OBIOHA ANNE', 'OLANAOKA OLANREWAJU YEMISI'),
  (197, 'IMFB/26/0510', 'UTOMWEN JENNIFER ENORENSE', 'UNCONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'MUSHIN', 'F', 'j.utomwen@infinitymfb.com', 'ALONGE MARIAM', 'OBILOR IFEANYI', 'OLANAOKA OLANREWAJU YEMISI'),
  (198, 'IMFB/26/0511', 'ADEKEYE ADELEKE EMMAUNEL', 'UNCONFIRMED', 'BRANCH MANAGER', 'CREDIT & MARKETING', 'KOLA', 'M', 'a.adekeye@infinitymfb,com', 'OJABINENI MOSUN', 'ADEKEYE ADELEKE EMMANUEL', 'OLANAOKA OLANREWAJU YEMISI'),
  (199, 'IMFB/26/0512', 'ISHOLA ISLAMIYA FUNMILAYO', 'UNCONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'OSHODI', 'F', 'i.ishola@infinitymfb.com', 'ENYINNAYA GLORIA IHUOMA', 'OBILOR IFEANYI', 'OLANAOKA OLANREWAJU YEMISI'),
  (200, 'IMFB/26/0514', 'IKUJUNI AYOWAMIRI ESTHER', 'UNCONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'KETU', 'F', 'a.ikujuni@infinitymfb.com', 'DISU HANNAH', 'ADENLE ADEWALE OLUWAROTIMI', 'OLANAOKA OLANREWAJU YEMISI'),
  (201, 'IMFB/26/0515', 'OKERE PATRICK JOSEPH', 'UNCONFIRMED', 'BRANCH MANAGER', 'CREDIT & MARKETING', 'TRADE FAIR', 'M', 'p.okeke@infinitymfb.com', 'OBILOR IFEANYIN', 'OLANAOKA OLANREWAJU YEMISI', null),
  (202, 'IMFB/26/0516', 'OGBON-OYE DADA OYE', 'UNCONFIRMED', 'DRIVER', 'ADMINISTRATION', 'IKORODU', 'M', 'N/A', 'OJABINENI MOSUN', 'ORUSOSO  ISIOMA-NWALIGBE', 'HRM'),
  (203, 'IMFB/26/0517', 'OJAJUNI ADELEKE GODWIN', 'UNCONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'ILE-EPO', 'M', 'g.ojajuni@infinitymfb.com', 'ADELEKE ADEKEYE', 'OJABINENI MOSUN', 'OLANAOKA OLANREWAJU YEMISI'),
  (204, 'IMFB/26/0518', 'ADEOTI MONSURAT FUNMILAYO', 'UNCONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'KETU', 'F', 'm.adeoti@infinitymfb.com', 'DISU HANNAH', 'ADENLE ADEWALE OLUWAROTIMI', 'OLANAOKA OLANREWAJU YEMISI'),
  (205, 'IMFB/26/0519', 'OYEWUNMI BAMIDELE MARTINS', 'UNCONFIRMED', 'COMPLIANCE OFFICER', 'RISK & COMPLIANCE', 'OSHODI & IKEJA', 'M', 'b.oyewunmu@infinitymfb.com', 'BANKOLE TEMITOPE', 'ABIWON TOLULOPE', null),
  (206, 'IMFB/26/0520', 'ROBIU HAJARA OMOWUNMI', 'UNCONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'HEAD OFFICE', 'F', 'o.rabiu@infinitymfb.com', 'ONUMAJULU VICTOR', 'ADENLE ADEWALE OLUWAROTIMI', 'OLANAOKA OLANREWAJU YEMISI'),
  (207, 'IMFB/26/0521', 'BABATUNDE KEMI KEHINDE', 'UNCONFIRMED', 'WHOLESALE LENDING EXECUTIVE', 'CREDIT & MARKETING', 'HEAD OFFICE', 'F', 'k.babatunde@infinitymfb.com', 'UKUAGHE JUDE', 'AJISEGBEDE GBEMI', null),
  (208, 'IMFB/26/0522', 'SHITTU KOREDE ABDULRAHAM', 'UNCONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'AJAH', 'M', 'a.shittu@infinitymfb.com', 'ABAYOMI ADEBAYO', 'OBIOHA ANNE', 'OLANAOKA OLANREWAJU YEMISI'),
  (209, 'IMFB/26/0523', 'COLLINS LUCIA  EGONDU', 'UNCONFIRMED', 'CUSTOMER SERVICE OFFICER', 'OPERATIONS', 'ILE-EPO', 'F', 'l.egondu@infinitymfb.com', 'UGUTE FEJIRO', null, null),
  (210, 'IMFB/26/0524', 'REKEDEI MAVIS PREKEME', 'UNCONFIRMED', 'SENIOR LEGAL OFFICER', 'LEGAL', 'HEAD OFFICE', 'M', 'm.rekedei@infinitymfb.com', 'AKOWE JACOB', null, null),
  (211, 'IMFB/26/0525', 'AWOSEYI DAMILOLA MICHAEL', 'UNCONFIRMED', 'WHOLESALE LENDING EXECUTIVE', 'CREDIT & MARKETING', 'HEAD OFFICE', 'M', 'd.awoseyi@infinitymfb.com', 'JUDE UKUAGHE', 'AJISEGBEDE GBEMI', null),
  (212, 'IMFB/26/0526', 'IWOLOMA CLINTON TAMUNOSIKI', 'UNCONFIRMED', 'IT AUTOMATION SPECIALIST OFFICER', 'E-BUSINESS', 'HEAD OFFICE', 'M', 'c.iwoloma@infinitymfb.com', 'OZIOKO COSMOS', null, null),
  (213, 'IMFB/26/0527', 'EZAIGWU JOHN', 'UNCONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'AGEGE', 'M', 'j.ezaigwu@infinitymfb.com', 'ADINOGE ESTHER', 'ADENLE ADEWALE OLUWAROTIMI', 'OLANAOKA OLANREWAJU YEMISI'),
  (214, 'IMFB/26/0528', 'KAYODE VICTORIA ADEOLA', 'UNCONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'AGEGE', 'F', 'v.kayode@infinitymfb.com', 'ADINOGE ESTHER', 'ADENLE ADEWALE OLUWAROTIMI', 'OLANAOKA OLANREWAJU YEMISI'),
  (215, 'IMFB/26/0529', 'OGBONNA RUTH UKAMAKA', 'UNCONFIRMED', 'LOAN OFFICER', 'CREDIT & MARKETING', 'LAGOS ISLAND 1', 'F', 'r.ogbonna@infinitymfb.com', 'ONI JOHN', 'OBIOHA ANNE', 'OLANAOKA OLANREWAJU YEMISI');
do $$
begin
  if (select count(*) from _it_automation_source) <> 215 then
    raise exception 'IT_AUTOMATION_LIST contains % rows; expected 215. No data was changed.',
      (select count(*) from _it_automation_source);
  end if;
end;
$$;

-- Rows whose staff_id is shared by more than one distinct employee in the
-- source (a genuine HR data conflict). Excluded from the employee upsert
-- below; reported at the end instead of guessing which employee owns the id.
create temporary table _it_duplicate_staff_ids as
select staff_id
from _it_automation_source
group by staff_id
having count(*) > 1;

create temporary table _it_automation_source_clean on commit preserve rows as
select s.*
from _it_automation_source s
where s.staff_id not in (select staff_id from _it_duplicate_staff_ids);

create unique index if not exists uq_employees_staff_id
  on public.employees (staff_id)
  where staff_id is not null;

create temporary table _it_branch_results (branch_name text, action text) on commit preserve rows;
do $$
declare
  r record;
  v_branch_id uuid;
begin
  for r in
    select distinct on (lower(trim(branch_name))) trim(branch_name) as branch_name
    from _it_automation_source
    order by lower(trim(branch_name)), sn
  loop
    select b.id into v_branch_id
    from public.branches b
    where lower(trim(b.branch_name)) = lower(trim(r.branch_name))
    order by b.created_at nulls first, b.id
    limit 1;

    if v_branch_id is null then
      insert into public.branches (branch_name, status)
      values (r.branch_name, 'active')
      returning id into v_branch_id;
      insert into _it_branch_results values (r.branch_name, 'new');
    else
      update public.branches
      set branch_name = r.branch_name, status = 'active', updated_at = now()
      where id = v_branch_id;
      insert into _it_branch_results values (r.branch_name, 'updated');
    end if;
  end loop;
end;
$$;

insert into public.departments (code, name, is_active)
select distinct
  upper(regexp_replace(trim(department), '[^A-Za-z0-9]+', '_', 'g')),
  trim(department),
  true
from _it_automation_source
on conflict (code) do update set name = excluded.name, is_active = true;

insert into public.designations (title, department, category, is_active)
select distinct trim(designation), trim(department), trim(department), true
from _it_automation_source
on conflict (title, department) do update set is_active = true;

insert into public.employees (
  full_name, email, phone, department, "position", gender,
  staff_id, employee_number, employee_code, branch, branch_id,
  confirmation_status, employment_status, designation_id,
  source, import_source, imported_from_bank_master, updated_at
)
select
  s.full_name,
  case when lower(trim(s.email)) in ('', 'n/a') then null else trim(both ',' from lower(trim(s.email))) end,
  null,
  s.department,
  s.designation,
  nullif(s.gender, ''),
  s.staff_id,
  s.staff_id,
  s.staff_id,
  s.branch_name,
  b.id,
  s.confirmation_status,
  'active',
  d.id,
  'bank_master_import',
  'IT_AUTOMATION_LIST',
  true,
  now()
from _it_automation_source_clean s
left join lateral (
  select id from public.branches b
  where lower(trim(b.branch_name)) = lower(trim(s.branch_name))
  order by b.created_at nulls first, b.id
  limit 1
) b on true
left join public.designations d
  on d.title = s.designation and d.department = s.department
on conflict (staff_id) where staff_id is not null do update set
  full_name = excluded.full_name,
  email = excluded.email,
  department = excluded.department,
  "position" = excluded."position",
  gender = excluded.gender,
  employee_number = excluded.employee_number,
  employee_code = excluded.employee_code,
  branch = excluded.branch,
  branch_id = excluded.branch_id,
  confirmation_status = excluded.confirmation_status,
  employment_status = excluded.employment_status,
  designation_id = excluded.designation_id,
  source = 'bank_master_import',
  import_source = 'IT_AUTOMATION_LIST',
  imported_from_bank_master = true,
  updated_at = now();

create temporary table _it_employee_map on commit preserve rows as
select s.*, e.id as employee_id
from _it_automation_source_clean s
join public.employees e on e.staff_id = s.staff_id;

delete from public.employee_supervisors es
using _it_employee_map m
where es.employee_id = m.employee_id;

do $$
declare
  r record;
  v_level integer;
  v_source_name text;
  v_supervisor_id uuid;
  v_match_count integer;
begin
  for r in select * from _it_employee_map loop
    for v_level in 1..3 loop
      v_source_name := case v_level when 1 then nullif(trim(r.supervisor1) , '') when 2 then nullif(trim(r.supervisor2), '') else nullif(trim(r.supervisor3), '') end;
      if v_source_name is null then continue; end if;

      select e.id into v_supervisor_id
      from _it_employee_map m
      join public.employees e on e.id = m.employee_id
      where lower(trim(e.full_name)) = lower(v_source_name)
      limit 1;

      if v_supervisor_id is null then
        select count(*) into v_match_count
        from _it_employee_map m
        join public.employees e on e.id = m.employee_id
        where regexp_split_to_array(trim(regexp_replace(lower(v_source_name), '[^a-z0-9]+', ' ', 'g')), '\s+')
          <@ regexp_split_to_array(trim(regexp_replace(lower(e.full_name), '[^a-z0-9]+', ' ', 'g')), '\s+');
        if v_match_count = 1 then
          select e.id into v_supervisor_id
          from _it_employee_map m
          join public.employees e on e.id = m.employee_id
          where regexp_split_to_array(trim(regexp_replace(lower(v_source_name), '[^a-z0-9]+', ' ', 'g')), '\s+')
            <@ regexp_split_to_array(trim(regexp_replace(lower(e.full_name), '[^a-z0-9]+', ' ', 'g')), '\s+')
          limit 1;
        end if;
      end if;

      if v_supervisor_id is not null then
        insert into public.employee_supervisors (
          employee_id, supervisor_employee_id, level, supervisor_title,
          effective_from, source
        ) values (
          r.employee_id, v_supervisor_id, v_level, v_source_name,
          current_date, 'IT_AUTOMATION_LIST'
        ) on conflict (employee_id, supervisor_employee_id, level) do update set
          supervisor_title = excluded.supervisor_title,
          effective_from = excluded.effective_from,
          source = excluded.source;

        update public.hierarchy_exceptions
        set status = 'resolved', resolution = jsonb_build_object('resolved_employee_id', v_supervisor_id), resolved_at = now()
        where employee_id = r.employee_id and source_supervisor_name = v_source_name and level = v_level;
      else
        insert into public.hierarchy_exceptions (
          employee_id, source_supervisor_name, level, reason, status
        ) values (
          r.employee_id, v_source_name, v_level,
          'Supervisor name did not resolve uniquely within this import.', 'open'
        ) on conflict (employee_id, source_supervisor_name, level) do update set
          reason = excluded.reason, status = 'open', resolution = null,
          resolved_by = null, resolved_at = null;
      end if;
      v_supervisor_id := null;
    end loop;
  end loop;
end;
$$;

commit;

-- Verification/report queries. Branches absent from this import are flagged,
-- never deleted. Duplicate-staff_id rows are flagged, never guessed at.
select 'source_rows' as metric, count(*)::text as value from _it_automation_source
union all
select 'employee_rows_matching_source', count(*)::text from public.employees e where e.staff_id in (select staff_id from _it_automation_source_clean)
union all
select 'unresolved_supervisor_links', count(*)::text from public.hierarchy_exceptions h where h.status = 'open' and h.employee_id in (select employee_id from _it_employee_map)
union all
select 'duplicate_staff_id_conflicts_excluded', count(*)::text from _it_automation_source where staff_id in (select staff_id from _it_duplicate_staff_ids);

select s.sn, s.staff_id, s.full_name, s.designation, s.branch_name
from _it_automation_source s
where s.staff_id in (select staff_id from _it_duplicate_staff_ids)
order by s.staff_id, s.sn;

select b.branch_name as branch_in_db_not_in_import
from public.branches b
where not exists (
  select 1 from _it_automation_source s
  where lower(trim(s.branch_name)) = lower(trim(b.branch_name))
)
order by b.branch_name;