// ============================================================================
// Leave Schedule Planner exports (PDF / Excel / print)
// ============================================================================
// The PDF is a REAL structured document generated with jsPDF - a branded cover
// block, a capacity summary, a paginated table and a warnings section. It is
// NOT a screenshot of the on-screen calendar and not a DOM capture.
//
// The Excel workbook uses the xlsx dependency the platform already has (see
// src/lib/payrollExcel.js): one sheet per audience, real headers and column
// widths rather than raw database columns.
import { jsPDF } from 'jspdf'
import * as XLSX from 'xlsx'
import { formatLeaveRange } from './leavePlannerService'

const BRAND = { green: [0, 153, 68], slate: [51, 65, 85], muted: [120, 130, 145] }
const COMPANY = 'Infinity Microfinance Bank'
const stamp = () => new Date().toISOString().slice(0, 10)

// ---------------------------------------------------------------------------
// Shared shaping. Pure, so it is easy to reason about and to test.
export function buildEmployeeSummary(entries = []) {
  const byEmployee = new Map()
  for (const e of entries) {
    if (!byEmployee.has(e.employee_id)) {
      byEmployee.set(e.employee_id, {
        name: e.full_name,
        number: e.employee_number || '',
        department: e.department || '',
        branch: e.branch_name || '',
        position: e.position || '',
        onLeave: 0, upcoming: 0, pending: 0, completed: 0,
      })
    }
    const row = byEmployee.get(e.employee_id)
    if (e.planner_state === 'on_leave') row.onLeave += 1
    else if (e.planner_state === 'upcoming') row.upcoming += 1
    else if (e.planner_state === 'pending') row.pending += 1
    else row.completed += 1
  }
  return [...byEmployee.values()]
}

export function buildGroupSummary(entries = [], key = 'branch_name') {
  const groups = new Map()
  for (const e of entries) {
    const label = e[key] || 'Unassigned'
    if (!groups.has(label)) groups.set(label, { label, people: new Set(), total: 0 })
    const g = groups.get(label)
    g.people.add(e.full_name)
    g.total += 1
  }
  return [...groups.values()].map((g) => ({
    label: g.label, employees: g.people.size, leaveRecords: g.total,
  }))
}

// ---------------------------------------------------------------------------
export function exportLeavePdf(data, { from, to }) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const pageW = doc.internal.pageSize.getWidth()
  const margin = 40
  let y = margin

  const newPage = () => { doc.addPage(); y = margin }
  const need = (h) => {
    if (y + h > doc.internal.pageSize.getHeight() - margin) newPage()
  }

  // ---- Branded cover block
  doc.setFillColor(...BRAND.green)
  doc.rect(0, 0, pageW, 76, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold').setFontSize(16)
  doc.text(COMPANY, margin, 34)
  doc.setFont('helvetica', 'normal').setFontSize(11)
  doc.text('Leave Schedule Report', margin, 54)

  doc.setTextColor(...BRAND.slate).setFontSize(9)
  y = 106
  doc.text(`Schedule period: ${formatLeaveRange(from, to)}`, margin, y); y += 14
  doc.text(`Generated: ${new Date().toLocaleString()}`, margin, y); y += 14
  doc.text('Generated by: InfinityCore Leave Schedule Planner', margin, y); y += 24

  const summary = data?.summary || {}

  // ---- Capacity summary
  doc.setFont('helvetica', 'bold').setFontSize(11)
  doc.text('Summary', margin, y); y += 16
  doc.setFont('helvetica', 'normal').setFontSize(9)
  doc.text([
    `Currently on leave: ${summary.currently_on_leave ?? 0}`,
    `Upcoming this week: ${summary.upcoming_this_week ?? 0}`,
    `Upcoming this month: ${summary.upcoming_this_month ?? 0}`,
    `Pending requests: ${summary.pending_requests ?? 0}`,
  ].join('     '), margin, y)
  y += 26

  // ---- Capacity warnings
  const conflicts = (data?.capacity || []).filter((c) => c.is_conflict)
  if (conflicts.length) {
    need(60)
    doc.setFont('helvetica', 'bold').setFontSize(11)
    doc.text('Capacity warnings', margin, y); y += 16
    doc.setFont('helvetica', 'normal').setFontSize(9).setTextColor(180, 30, 30)
    const seen = new Set()
    for (const c of conflicts) {
      if (seen.has(c.branch_name)) continue
      seen.add(c.branch_name)
      need(14)
      doc.text(
        `- ${c.branch_name}: ${c.on_leave_count} on leave against a capacity of ${c.configured_capacity}`,
        margin, y,
      )
      y += 13
    }
    doc.setTextColor(...BRAND.slate)
    y += 14
  }

  // ---- Paginated schedule table
  need(40)
  doc.setFont('helvetica', 'bold').setFontSize(11)
  doc.text('Schedule', margin, y); y += 18

  const cols = [margin, margin + 130, margin + 250, margin + 350, margin + 430]
  const headers = ['Employee', 'Department', 'Branch', 'Period', 'Status']

  const drawHeader = () => {
    doc.setFillColor(245, 247, 250)
    doc.rect(margin, y - 11, pageW - margin * 2, 18, 'F')
    doc.setFont('helvetica', 'bold').setFontSize(8)
    headers.forEach((h, i) => doc.text(h, cols[i], y + 1))
    y += 16
  }
  drawHeader()

  for (const e of data?.entries || []) {
    need(16)
    if (y > doc.internal.pageSize.getHeight() - margin - 20) {
      newPage(); drawHeader()
    }
    doc.setFont('helvetica', 'normal').setFontSize(8)
    doc.text(String(e.full_name || '').slice(0, 26), cols[0], y)
    doc.text(String(e.department || '-').slice(0, 20), cols[1], y)
    doc.text(String(e.branch_name || '-').slice(0, 20), cols[2], y)
    doc.text(formatLeaveRange(e.start_date, e.end_date).slice(0, 18), cols[3], y)
    doc.text(String(e.status || ''), cols[4], y)
    y += 14
  }

  // ---- Footer on every page
  const pages = doc.getNumberOfPages()
  for (let i = 1; i <= pages; i += 1) {
    doc.setPage(i)
    doc.setFontSize(7).setTextColor(...BRAND.muted)
    doc.text(
      `${COMPANY} - Leave Schedule Report - page ${i} of ${pages}`,
      margin, doc.internal.pageSize.getHeight() - 20,
    )
  }

  doc.save(`leave-schedule-${from}_to_${to}.pdf`)
}

// ---------------------------------------------------------------------------
function sheetFromRows(rows, widths) {
  const ws = XLSX.utils.json_to_sheet(rows)
  if (widths) ws['!cols'] = widths.map((w) => ({ wch: w }))
  return ws
}

export function exportLeaveExcel(data, { from, to }) {
  const wb = XLSX.utils.book_new()
  const entries = data?.entries || []

  XLSX.utils.book_append_sheet(wb, sheetFromRows(
    entries.map((e) => ({
      Employee: e.full_name,
      'Employee ID': e.employee_number,
      Department: e.department,
      Branch: e.branch_name,
      Position: e.position,
      'Leave type': e.leave_type,
      'Start date': e.start_date,
      'End date': e.end_date,
      'Working days': e.working_days,
      Status: e.status,
    })),
    [26, 14, 18, 18, 20, 14, 12, 12, 12, 12],
  ), 'Leave Schedule')

  XLSX.utils.book_append_sheet(wb, sheetFromRows(
    buildEmployeeSummary(entries),
    [26, 14, 18, 18, 20, 10, 10, 10, 10],
  ), 'Employee Summary')

  XLSX.utils.book_append_sheet(wb, sheetFromRows(
    buildGroupSummary(entries, 'department'), [26, 12, 16],
  ), 'Department Summary')

  XLSX.utils.book_append_sheet(wb, sheetFromRows(
    buildGroupSummary(entries, 'branch_name'), [26, 12, 16],
  ), 'Branch Summary')

  XLSX.utils.book_append_sheet(wb, sheetFromRows(
    (data?.capacity || []).map((c) => ({
      Branch: c.branch_name,
      Date: c.day,
      'On leave': c.on_leave_count,
      Headcount: c.headcount,
      Capacity: c.configured_capacity ?? 'Not configured',
      Status: c.is_conflict ? 'CONFLICT'
        : (c.configured_capacity == null ? '' : 'Within capacity'),
    })),
    [22, 12, 10, 12, 18, 16],
  ), 'Capacity Analysis')

  const summary = data?.summary || {}
  XLSX.utils.book_append_sheet(wb, sheetFromRows([
    { Metric: 'Schedule period', Value: formatLeaveRange(from, to) },
    { Metric: 'Generated', Value: stamp() },
    { Metric: 'Currently on leave', Value: summary.currently_on_leave ?? 0 },
    { Metric: 'Upcoming this week', Value: summary.upcoming_this_week ?? 0 },
    { Metric: 'Upcoming this month', Value: summary.upcoming_this_month ?? 0 },
    { Metric: 'Pending requests', Value: summary.pending_requests ?? 0 },
    { Metric: 'Capacity conflicts', Value: (data?.capacity || []).filter((c) => c.is_conflict).length },
  ], [24, 26]), 'Overview')

  XLSX.writeFile(wb, `leave-schedule-${from}_to_${to}.xlsx`)
}

// ---------------------------------------------------------------------------
// Print view. The planner's controls are already hidden by print: classes, so
// this only needs to name the window.
export function printLeaveSchedule() {
  window.print()
}
