/**
 * Role definitions and metadata for the role-aware application
 * Replaces hardcoded role strings throughout the app
 */

export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  BRANCH_MANAGER: 'branch_manager',
  AREA_MANAGER: 'area_manager',
  HEAD_OF_BUSINESS: 'head_of_business',
  HEAD_OF_OPERATIONS: 'head_of_operations',
  HEAD_OF_E_BUSINESS: 'head_of_e_business',
  FINANCIAL_CONTROLLER: 'financial_controller',
  HEAD_OF_RISK_COMPLIANCE: 'head_of_risk_compliance',
  HEAD_OF_LEGAL: 'head_of_legal',
  HEAD_OF_AUDIT: 'head_of_audit',
  LOAN_OFFICER: 'loan_officer',
  RELATIONSHIP_MANAGER: 'relationship_manager',
  CUSTOMER_SERVICE: 'customer_service',
  HR_MANAGER: 'hr_manager',
  HR_OFFICER: 'hr_officer',
  STAFF: 'staff',
  CUSTOMER: 'customer',
}

// Role hierarchy - higher number = more power
export const ROLE_HIERARCHY = {
  [ROLES.SUPER_ADMIN]: 100,
  [ROLES.ADMIN]: 90,
  [ROLES.HEAD_OF_E_BUSINESS]: 80,
  [ROLES.HEAD_OF_OPERATIONS]: 79,
  [ROLES.HEAD_OF_BUSINESS]: 78,
  [ROLES.AREA_MANAGER]: 77,
  [ROLES.BRANCH_MANAGER]: 76,
  [ROLES.FINANCIAL_CONTROLLER]: 75,
  [ROLES.HEAD_OF_RISK_COMPLIANCE]: 74,
  [ROLES.HEAD_OF_LEGAL]: 73,
  [ROLES.HEAD_OF_AUDIT]: 72,
  [ROLES.LOAN_OFFICER]: 60,
  [ROLES.RELATIONSHIP_MANAGER]: 60,
  [ROLES.HR_MANAGER]: 60,
  [ROLES.CUSTOMER_SERVICE]: 50,
  [ROLES.HR_OFFICER]: 50,
  [ROLES.STAFF]: 40,
  [ROLES.CUSTOMER]: 10,
}

// Role metadata for UI display
export const ROLE_METADATA = {
  [ROLES.SUPER_ADMIN]: {
    label: 'Super Admin',
    description: 'Full system access, can switch all views',
    primaryModule: 'admin',
    color: '#7c3aed',
    icon: 'Shield',
  },
  [ROLES.ADMIN]: {
    label: 'Admin',
    description: 'System administration and user management',
    primaryModule: 'admin',
    color: '#7c3aed',
    icon: 'Lock',
  },
  [ROLES.BRANCH_MANAGER]: {
    label: 'Branch Manager',
    description: 'Manage branch operations and staff',
    primaryModule: 'dashboard',
    color: '#2563eb',
    icon: 'Building2',
  },
  [ROLES.AREA_MANAGER]: {
    label: 'Area Manager',
    description: 'Oversees multiple branches within a region',
    primaryModule: 'dashboard',
    color: '#1d4ed8',
    icon: 'Map',
  },
  [ROLES.HEAD_OF_BUSINESS]: {
    label: 'Head of Business',
    description: 'Senior business leadership approval',
    primaryModule: 'dashboard',
    color: '#1e40af',
    icon: 'Briefcase',
  },
  [ROLES.HEAD_OF_OPERATIONS]: {
    label: 'Head of Operations',
    description: 'Oversees daily banking operations, attendance and staff workflow',
    primaryModule: 'my-work',
    color: '#2563eb',
    icon: 'Workflow',
  },
  [ROLES.HEAD_OF_E_BUSINESS]: {
    label: 'Head of E-Business',
    description: 'Owns digital banking channels and electronic product oversight',
    primaryModule: 'my-work',
    color: '#0e7490',
    icon: 'Globe',
  },
  [ROLES.FINANCIAL_CONTROLLER]: {
    label: 'Financial Controller',
    description: 'Owns accounting, financial control and BankOne reconciliation',
    primaryModule: 'payroll',
    color: '#b45309',
    icon: 'Calculator',
  },
  [ROLES.HEAD_OF_RISK_COMPLIANCE]: {
    label: 'Head of Risk & Compliance',
    description: 'Oversees risk, compliance and regulatory reporting',
    primaryModule: 'reports',
    color: '#be123c',
    icon: 'ShieldAlert',
  },
  [ROLES.HEAD_OF_LEGAL]: {
    label: 'Head of Legal',
    description: 'Owns legal, documentation and recovery oversight',
    primaryModule: 'my-work',
    color: '#4338ca',
    icon: 'Scale',
  },
  [ROLES.HEAD_OF_AUDIT]: {
    label: 'Head of Audit',
    description: 'Independent assurance and audit oversight',
    primaryModule: 'reports',
    color: '#334155',
    icon: 'SearchCheck',
  },
  [ROLES.LOAN_OFFICER]: {
    label: 'Loan Officer',
    description: 'Manage loan applications and assessments',
    primaryModule: 'loans',
    color: '#059669',
    icon: 'Landmark',
  },
  [ROLES.RELATIONSHIP_MANAGER]: {
    label: 'Relationship Manager',
    description: 'Manage customer relationships',
    primaryModule: 'customers',
    color: '#0891b2',
    icon: 'Users',
  },
  [ROLES.CUSTOMER_SERVICE]: {
    label: 'Customer Service',
    description: 'Handle customer support and inquiries',
    primaryModule: 'support',
    color: '#f59e0b',
    icon: 'Headphones',
  },
  [ROLES.HR_MANAGER]: {
    label: 'HR Manager',
    description: 'Manage recruitment and HR processes',
    primaryModule: 'hr',
    color: '#dc2626',
    icon: 'Users',
  },
  [ROLES.HR_OFFICER]: {
    label: 'HR Officer',
    description: 'HR administrative tasks',
    primaryModule: 'hr',
    color: '#dc2626',
    icon: 'Briefcase',
  },
  [ROLES.STAFF]: {
    label: 'Staff',
    description: 'General staff member',
    primaryModule: 'dashboard',
    color: '#6b7280',
    icon: 'User',
  },
  [ROLES.CUSTOMER]: {
    label: 'Customer',
    description: 'External customer',
    primaryModule: 'customer-dashboard',
    color: '#10b981',
    icon: 'User',
  },
}

// Permissions by role
export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: [
    'customers.read',
    'customers.create',
    'customers.update',
    'customers.delete',
    'loans.read',
    'loans.create',
    'loans.assess',
    'loans.approve_low',
    'loans.approve_medium',
    'loans.approve_high',
    'loans.disburse',
    'documents.upload',
    'documents.read',
    'documents.verify',
    'documents.delete',
    'hr.jobs.create',
    'hr.jobs.manage',
    'hr.applications.read',
    'hr.applications.screen',
    'hr.assessments.create',
    'hr.interviews.schedule',
    'hr.hire',
    'hr.leave.manage',
    'hr.payroll.read',
    'hr.offer_letters.read',
    'hr.onboarding.read',
    'hr.onboarding.manage',
    'hr.employee.read',
    'hr.employee.update',
    'hr.attendance.self',
    'hr.attendance.manage',
    'hr.settings.manage',
    'payroll.manage',
    'payroll.push',
    'payroll.approve',
    'data.import.view',
    'data.import.execute',
    'branches.read',
    'support.create',
    'support.read',
    'support.resolve',
    'admin.manage_users',
    'admin.view_audit',
    'admin.manage_config',
    'admin.platform.reset',
    'reports.read',
    'bankone.import',
    'bankone.read',
    'reconciliation.manage',
    'reconciliation.read',
    'performance.manage',
    'performance.read',
    'appraisal.manage',
    'appraisal.read',
    'hr_config.manage',
    'work.tasks.manage',
    'work.kpis.manage',
    'work.targets.manage',
    'work.plans.manage',
    'work.reports.review',
    'work.team.performance',
    'attendance.config.manage',
    'hr.org.manage',
    'medical.read',
    'medical.manage',
    'hr.training.read',
    'hr.training.manage',
    'workforce.manhour.read',
    'attendance.terminal',
  ],
  [ROLES.ADMIN]: [
    'customers.read',
    'customers.create',
    'customers.update',
    'customers.delete',
    'loans.read',
    'loans.create',
    'loans.assess',
    'loans.approve_low',
    'loans.approve_medium',
    'loans.approve_high',
    'loans.disburse',
    'documents.upload',
    'documents.read',
    'documents.verify',
    'documents.delete',
    'hr.jobs.create',
    'hr.jobs.manage',
    'hr.applications.read',
    'hr.applications.screen',
    'hr.assessments.create',
    'hr.interviews.schedule',
    'hr.hire',
    'hr.leave.manage',
    'hr.payroll.read',
    'hr.offer_letters.read',
    'hr.onboarding.read',
    'hr.onboarding.manage',
    'hr.employee.read',
    'hr.employee.update',
    'hr.attendance.self',
    'hr.attendance.manage',
    'hr.settings.manage',
    'payroll.manage',
    'payroll.push',
    'payroll.approve',
    'data.import.view',
    'data.import.execute',
    'branches.read',
    'support.create',
    'support.read',
    'support.resolve',
    'admin.manage_users',
    'admin.view_audit',
    'admin.manage_config',
    'reports.read',
    'bankone.import',
    'bankone.read',
    'reconciliation.manage',
    'reconciliation.read',
    'performance.manage',
    'performance.read',
    'appraisal.manage',
    'appraisal.read',
    'hr_config.manage',
    'work.tasks.manage',
    'work.kpis.manage',
    'work.targets.manage',
    'work.plans.manage',
    'work.reports.review',
    'work.team.performance',
    'attendance.config.manage',
    'hr.org.manage',
    'medical.read',
    'medical.manage',
    'hr.training.read',
    'hr.training.manage',
    'workforce.manhour.read',
    'attendance.terminal',
  ],
  [ROLES.BRANCH_MANAGER]: [
    'customers.read',
    'customers.update',
    'loans.read',
    'loans.assess',
    'loans.approve_medium',
    'loans.disburse',
    'documents.read',
    'branches.read',
    'reports.read',
    'support.read',
    'hr.attendance.self',
    'hr.attendance.manage',
    'work.tasks.manage',
    'work.kpis.manage',
    'work.targets.manage',
    'work.plans.manage',
    'work.reports.review',
    'work.team.performance',
    'hr.training.read',
    'workforce.manhour.read',
    'attendance.terminal',
  ],
  [ROLES.AREA_MANAGER]: [
    'customers.read',
    'loans.read',
    'loans.approve_medium',
    'loans.disburse',
    'hr.leave.manage',
    'branches.read',
    'reports.read',
    'hr.attendance.self',
    'hr.training.read',
    'workforce.manhour.read',
    'attendance.terminal',
  ],
  [ROLES.HEAD_OF_BUSINESS]: [
    'customers.read',
    'loans.read',
    'loans.approve_high',
    'loans.disburse',
    'hr.leave.manage',
    'branches.read',
    'reports.read',
    'hr.attendance.self',
    'hr.training.read',
    'workforce.manhour.read',
    'attendance.terminal',
  ],
  [ROLES.HEAD_OF_OPERATIONS]: [
    'customers.read',
    'loans.read',
    'hr.leave.manage',
    'branches.read',
    'reports.read',
    'hr.attendance.self',
    'hr.attendance.manage',
    'attendance.terminal',
    'hr.training.read',
    'workforce.manhour.read',
  ],
  [ROLES.HEAD_OF_E_BUSINESS]: [
    'customers.read',
    'loans.read',
    'branches.read',
    'reports.read',
    'hr.attendance.self',
    'attendance.terminal',
    'bankone.read',
    'hr.training.read',
    'workforce.manhour.read',
  ],
  [ROLES.FINANCIAL_CONTROLLER]: [
    'customers.read',
    'loans.read',
    'branches.read',
    'reports.read',
    'hr.attendance.self',
    'payroll.manage',
    'bankone.read',
    'reconciliation.read',
    'hr.training.read',
    'workforce.manhour.read',
  ],
  [ROLES.HEAD_OF_RISK_COMPLIANCE]: [
    'customers.read',
    'loans.read',
    'branches.read',
    'reports.read',
    'hr.attendance.self',
    'admin.view_audit',
    'hr.training.read',
    'workforce.manhour.read',
  ],
  [ROLES.HEAD_OF_LEGAL]: [
    'customers.read',
    'loans.read',
    'documents.read',
    'branches.read',
    'reports.read',
    'hr.attendance.self',
    'hr.training.read',
    'workforce.manhour.read',
  ],
  [ROLES.HEAD_OF_AUDIT]: [
    'customers.read',
    'loans.read',
    'branches.read',
    'reports.read',
    'admin.view_audit',
    'hr.attendance.self',
    'hr.training.read',
    'workforce.manhour.read',
  ],
  [ROLES.LOAN_OFFICER]: [
    'customers.read',
    'loans.read',
    'loans.assess',
    'loans.approve_low',
    'loans.disburse',
    'documents.upload',
    'documents.read',
    'documents.verify',
    'support.read',
    'hr.attendance.self',
  ],
  [ROLES.RELATIONSHIP_MANAGER]: [
    'customers.read',
    'customers.update',
    'loans.read',
    'documents.read',
    'support.create',
    'support.read',
    'hr.attendance.self',
  ],
  [ROLES.CUSTOMER_SERVICE]: [
    'customers.read',
    'support.create',
    'support.read',
    'support.resolve',
    'hr.attendance.self',
  ],
  [ROLES.HR_MANAGER]: [
    'hr.jobs.create',
    'hr.jobs.manage',
    'hr.applications.read',
    'hr.applications.screen',
    'hr.assessments.create',
    'hr.interviews.schedule',
    'hr.hire',
    'hr.leave.manage',
    'hr.payroll.read',
    'hr.offer_letters.read',
    'hr.onboarding.read',
    'hr.onboarding.manage',
    'hr.employee.read',
    'hr.employee.update',
    'hr.attendance.self',
    'hr.attendance.manage',
    'hr.settings.manage',
    'payroll.manage',
    'payroll.push',
    'payroll.approve',
    'data.import.view',
    'branches.read',
    'reports.read',
    'bankone.import',
    'bankone.read',
    'reconciliation.manage',
    'reconciliation.read',
    'performance.manage',
    'performance.read',
    'appraisal.manage',
    'appraisal.read',
    'hr_config.manage',
    'work.tasks.manage',
    'work.kpis.manage',
    'work.targets.manage',
    'work.plans.manage',
    'work.reports.review',
    'work.team.performance',
    'hr.org.manage',
    'medical.read',
    'medical.manage',
    'hr.training.read',
    'hr.training.manage',
    'workforce.manhour.read',
    'attendance.terminal',
  ],
  [ROLES.HR_OFFICER]: [
    'hr.applications.read',
    'hr.assessments.create',
    'hr.interviews.schedule',
    'hr.offer_letters.read',
    'hr.onboarding.read',
    'hr.employee.read',
    'hr.attendance.self',
    'hr.attendance.manage',
    'hr.payroll.read',
    'payroll.push',
    'bankone.read',
    'reconciliation.read',
    'performance.read',
    'appraisal.read',
    'medical.read',
    'hr.training.read',
  ],
  [ROLES.STAFF]: [
    'customers.read',
    'loans.read',
    'documents.upload',
    'hr.attendance.self',
  ],
  [ROLES.CUSTOMER]: [
    'customers.read', // Own customer data
    'loans.read', // Own loans
    'documents.upload', // Own documents
    'support.create',
    'support.read',
  ],
}

// Module navigation by role
export const ROLE_MODULES = {
  [ROLES.SUPER_ADMIN]: [
    'dashboard',
    'customers',
    'loans',
    'my-work',
    'hr',
    'support',
    'reports',
    'audit-logs',
    'users',
    'my_training',
  ],
  [ROLES.ADMIN]: [
    'dashboard',
    'customers',
    'loans',
    'my-work',
    'hr',
    'support',
    'reports',
    'audit-logs',
    'users',
    'my_training',
  ],
  [ROLES.BRANCH_MANAGER]: [
    'dashboard',
    'my-work',
    'customers',
    'loans',
    'support',
    'my_training',
  ],
  [ROLES.AREA_MANAGER]: [
    'dashboard',
    'my-work',
    'customers',
    'loans',
    'support',
    'my_training',
  ],
  [ROLES.HEAD_OF_BUSINESS]: [
    'dashboard',
    'my-work',
    'customers',
    'loans',
    'support',
    'reports',
    'my_training',
  ],
  [ROLES.HEAD_OF_OPERATIONS]: [
    'dashboard',
    'my-work',
    'customers',
    'loans',
    'support',
    'reports',
    'my_training',
  ],
  [ROLES.HEAD_OF_E_BUSINESS]: [
    'dashboard',
    'my-work',
    'customers',
    'loans',
    'reports',
    'my_training',
  ],
  [ROLES.FINANCIAL_CONTROLLER]: [
    'dashboard',
    'my-work',
    'customers',
    'loans',
    'reports',
    'my_training',
  ],
  [ROLES.HEAD_OF_RISK_COMPLIANCE]: [
    'dashboard',
    'my-work',
    'customers',
    'loans',
    'reports',
    'audit-logs',
    'my_training',
  ],
  [ROLES.HEAD_OF_LEGAL]: [
    'dashboard',
    'my-work',
    'customers',
    'loans',
    'my_training',
  ],
  [ROLES.HEAD_OF_AUDIT]: [
    'dashboard',
    'my-work',
    'customers',
    'loans',
    'reports',
    'audit-logs',
    'my_training',
  ],
  [ROLES.LOAN_OFFICER]: [
    'my-work',
    'loans',
    'customers',
    'my_training',
  ],
  [ROLES.RELATIONSHIP_MANAGER]: [
    'my-work',
    'customers',
    'loans',
    'my_training',
  ],
  [ROLES.CUSTOMER_SERVICE]: [
    'my-work',
    'support',
    'customers',
    'my_training',
  ],
  [ROLES.HR_MANAGER]: [
    'hr',
    'dashboard',
    'my_training',
  ],
  [ROLES.HR_OFFICER]: [
    'hr',
    'my_training',
  ],
  [ROLES.STAFF]: [
    'dashboard',
    'customers',
    'loans',
    'my_training',
  ],
  [ROLES.CUSTOMER]: [
    'customer-dashboard',
    'my-loans',
    'support',
  ],
}

// ------------------------------------------------------------------
// STAFF PROMOTION MATRIX — mirrors the DB trigger in
// schema_phase5_role_security.sql (enforce_role_change_policy).
// This copy is for UI purposes only (so a manager doesn't see options
// they can't actually use) — the DATABASE trigger is the real
// authority and rejects anything this matrix would incorrectly allow.
// ------------------------------------------------------------------
export function assignableRoles(actorRole) {
  if (actorRole === ROLES.SUPER_ADMIN) return Object.values(ROLES)
  if (actorRole === ROLES.ADMIN) return Object.values(ROLES).filter((r) => r !== ROLES.SUPER_ADMIN)
  if (actorRole === ROLES.AREA_MANAGER || actorRole === ROLES.HR_MANAGER) {
    return Object.values(ROLES).filter((r) => ![ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.AREA_MANAGER, ROLES.HEAD_OF_BUSINESS, ROLES.HEAD_OF_OPERATIONS, ROLES.HEAD_OF_E_BUSINESS, ROLES.FINANCIAL_CONTROLLER, ROLES.HEAD_OF_RISK_COMPLIANCE, ROLES.HEAD_OF_LEGAL, ROLES.HEAD_OF_AUDIT].includes(r))
  }
  if (actorRole === ROLES.BRANCH_MANAGER) {
    return [ROLES.STAFF, ROLES.LOAN_OFFICER, ROLES.RELATIONSHIP_MANAGER, ROLES.CUSTOMER_SERVICE]
  }
  return []
}
