import React from 'react'
import Logo from './Logo'

const fmtDate = (v) => (v ? new Date(v).toLocaleDateString() : '—')
const fmtMoney = (v) => (v != null && v !== '' ? `₦${Number(v).toLocaleString()}` : '—')

function Field({ label, value }) {
  return (
    <div>
      <p className="text-[10px] uppercase tracking-wider text-slate-400 font-medium mb-0.5">{label}</p>
      <p className="text-sm text-slate-800 leading-snug min-h-[1.25rem]">{value || '—'}</p>
    </div>
  )
}

function SectionTitle({ title, number }) {
  return (
    <div className="mt-6 mb-3 flex items-center gap-2">
      <span className="inline-flex items-center justify-center w-6 h-6 rounded bg-[#009944] text-white text-[11px] font-bold">{number}</span>
      <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wide border-b border-slate-200 flex-1 pb-1">{title}</h3>
    </div>
  )
}

export default function EmployeeRecordPrint({
  employee = {},
  education = [],
  workHistory = [],
  guarantors = [],
  fidelityBonds = [],
  documents = [],
  verifications = [],
  photoUrl = null,
}) {
  const emp = employee
  const initials = (emp.full_name || 'E').split(' ').filter(Boolean).slice(0, 2).map((n) => n[0]?.toUpperCase()).join('')
  const generatedAt = new Date().toLocaleString()
  const recordId = emp.employee_number || emp.employee_code || emp.id?.slice(0, 8) || 'N/A'

  return (
    <div className="print-area">
      <div className="w-full bg-white text-slate-800 text-[13px] leading-relaxed" style={{ fontFamily: 'ui-sans-serif, system-ui, sans-serif', padding: '32px 40px' }}>

        {/* HEADER */}
        <div className="flex items-start justify-between pb-4 border-b-2 border-[#009944]">
          <div className="flex items-center gap-4">
            <Logo size={48} variant="full" />
            <div>
              <h1 className="text-xl font-bold text-[#009944] leading-tight">Employee Personnel Record</h1>
              <p className="text-[11px] text-slate-400 mt-1">Confidential — HR Records</p>
            </div>
          </div>
          <div className="text-right flex flex-col items-end gap-2">
            {emp.photo_url || photoUrl ? (
              <img src={photoUrl} alt="Passport" className="w-20 h-24 rounded border border-slate-200 object-cover" />
            ) : (
              <div className="w-20 h-24 rounded border border-slate-200 bg-slate-50 flex items-center justify-center">
                <span className="text-2xl font-bold text-[#009944]">{initials}</span>
              </div>
            )}
            <div className="text-left text-xs space-y-0.5">
              <div><span className="text-slate-400">Record ID:</span> <span className="font-semibold">{recordId}</span></div>
              <div><span className="text-slate-400">Generated:</span> {generatedAt}</div>
              <div><span className="text-slate-400">Generated By:</span> InfinityCore HR</div>
            </div>
          </div>
        </div>

        {/* 1. PERSONAL */}
        <SectionTitle title="Personal Information" number={1} />
        <div className="grid grid-cols-4 gap-x-6 gap-y-2">
          <Field label="Full Name" value={emp.full_name} />
          <Field label="Email" value={emp.email} />
          <Field label="Phone" value={emp.phone} />
          <Field label="Date of Birth" value={fmtDate(emp.date_of_birth)} />
          <Field label="Sex" value={emp.sex} />
          <Field label="Nationality" value={emp.nationality} />
          <Field label="State of Origin" value={emp.state_of_origin} />
          <Field label="LGA" value={emp.lga} />
          <Field label="Town / City" value={emp.town} />
          <Field label="Religion" value={emp.religion} />
          <Field label="Denomination" value={emp.denomination} />
          <Field label="Marital Status" value={emp.marital_status} />
          <Field label="Residential Address" value={emp.residential_address} className="col-span-2" />
          <Field label="Number of Children" value={emp.number_of_children} />
          <Field label="Children Age Range" value={emp.children_age_range} />
        </div>

        {/* 2. EMPLOYMENT */}
        <SectionTitle title="Employment / HR Record" number={2} />
        <div className="grid grid-cols-4 gap-x-6 gap-y-2">
          <Field label="Employee Number" value={emp.employee_number} />
          <Field label="Staff ID" value={emp.staff_id} />
          <Field label="Employee Code" value={emp.employee_code} />
          <Field label="Department" value={emp.department} />
          <Field label="Position" value={emp.position} />
          <Field label="Employment Status" value={emp.employment_status} />
          <Field label="Employment Type" value={emp.employment_type} />
          <Field label="Hire Date" value={fmtDate(emp.hire_date)} />
          <Field label="Salary" value={fmtMoney(emp.salary)} />
          <Field label="Basic Salary" value={fmtMoney(emp.basic_salary)} />
          <Field label="Allowances" value={fmtMoney(emp.allowances)} />
          <Field label="HMO" value={emp.hmo} />
          <Field label="Branch" value={emp.branch} />
          <Field label="Branch Manager" value={emp.branch_manager_name} />
          <Field label="Area Manager" value={emp.area_manager_name} />
          <Field label="Bank Name" value={emp.bank_name} />
          <Field label="Account Number" value={emp.account_number} />
          <Field label="Pension ID" value={emp.pension_id} />
          <Field label="Tax ID" value={emp.tax_id} />
          <Field label="NHF ID" value={emp.nhf_id} />
        </div>

        {/* 3. NEXT OF KIN / EMERGENCY */}
        <SectionTitle title="Next of Kin & Emergency Contacts" number={3} />
        <div className="grid grid-cols-4 gap-x-6 gap-y-2">
          <Field label="Next of Kin Name" value={emp.next_of_kin_name} />
          <Field label="Next of Kin Phone" value={emp.next_of_kin_phone} />
          <Field label="Relationship" value={emp.next_of_kin_relationship} />
          <Field label="Next of Kin Address" value={emp.next_of_kin_address} />
          <Field label="Beneficiary Name" value={emp.beneficiary_name} />
          <Field label="Beneficiary Phone" value={emp.beneficiary_phone} />
          <Field label="Beneficiary Relationship" value={emp.beneficiary_relationship} />
          <Field label="Emergency Contact Name" value={emp.emergency_contact_name} />
          <Field label="Emergency Contact Phone" value={emp.emergency_contact_phone} />
        </div>

        {/* 4. EDUCATION */}
        {education.length > 0 && (
          <>
            <SectionTitle title="Education / Qualifications" number={4} />
            <div className="overflow-x-auto">
              <table className="w-full text-xs border-collapse">
                <thead>
                  <tr className="bg-slate-50 text-slate-500 text-left">
                    <th className="px-2 py-1 border border-slate-200 font-medium">Institution</th>
                    <th className="px-2 py-1 border border-slate-200 font-medium">Level</th>
                    <th className="px-2 py-1 border border-slate-200 font-medium">Field of Study</th>
                    <th className="px-2 py-1 border border-slate-200 font-medium">Period</th>
                    <th className="px-2 py-1 border border-slate-200 font-medium">Class / Degree</th>
                  </tr>
                </thead>
                <tbody>
                  {education.map((e) => (
                    <tr key={e.id}>
                      <td className="px-2 py-1 border border-slate-200">{e.institution}</td>
                      <td className="px-2 py-1 border border-slate-200">{e.education_level || '—'}</td>
                      <td className="px-2 py-1 border border-slate-200">{e.field_of_study || '—'}</td>
                      <td className="px-2 py-1 border border-slate-200">{e.from_year || '—'} — {e.to_year || '—'}</td>
                      <td className="px-2 py-1 border border-slate-200">{e.class_degree || '—'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </>
        )}

        {/* 5. WORK HISTORY */}
        {workHistory.length > 0 && (
          <>
            <SectionTitle title="Work History" number={5} />
            <div className="overflow-x-auto">
              <table className="w-full text-xs border-collapse">
                <thead>
                  <tr className="bg-slate-50 text-slate-500 text-left">
                    <th className="px-2 py-1 border border-slate-200 font-medium">Company</th>
                    <th className="px-2 py-1 border border-slate-200 font-medium">Position</th>
                    <th className="px-2 py-1 border border-slate-200 font-medium">Period</th>
                    <th className="px-2 py-1 border border-slate-200 font-medium">Reason for Leaving</th>
                  </tr>
                </thead>
                <tbody>
                  {workHistory.map((w) => (
                    <tr key={w.id}>
                      <td className="px-2 py-1 border border-slate-200">{w.company_name}</td>
                      <td className="px-2 py-1 border border-slate-200">{w.position || '—'}</td>
                      <td className="px-2 py-1 border border-slate-200">{fmtDate(w.start_date)} — {fmtDate(w.end_date)}</td>
                      <td className="px-2 py-1 border border-slate-200">{w.reason_for_leaving || '—'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </>
        )}

        {/* 6. GUARANTORS */}
        {guarantors.length > 0 && (
          <>
            <SectionTitle title="Guarantors" number={6} />
            <div className="grid grid-cols-2 gap-4">
              {guarantors.map((g) => (
                <div key={g.id} className="border border-slate-200 rounded p-3">
                  <p className="font-semibold text-sm text-slate-800">{g.full_name}</p>
                  <p className="text-xs text-slate-500 mt-1">Relationship: {g.relationship || '—'}</p>
                  <p className="text-xs text-slate-500">Phone: {g.phone || '—'}</p>
                  <p className="text-xs text-slate-500">Verification: {g.verification_status || 'pending'}</p>
                </div>
              ))}
            </div>
          </>
        )}

        {/* 7. DOCUMENTS */}
        {documents.length > 0 && (
          <>
            <SectionTitle title="Employee Documents" number={7} />
            <div className="text-xs space-y-1">
              {documents.map((d) => (
                <div key={d.id} className="flex items-center justify-between py-1 border-b border-slate-100 last:border-0">
                  <span>{d.file_name}</span>
                  <span className="text-slate-400">{d.document_type} — {d.verification_status || 'pending'}</span>
                </div>
              ))}
            </div>
          </>
        )}

        {/* 8. ONBOARDING / GUARANTOR VERIFICATIONS */}
        {verifications.length > 0 && (
          <>
            <SectionTitle title="Guarantor Verifications" number={8} />
            <div className="space-y-2">
              {verifications.map((v) => (
                <div key={v.id} className="flex items-center justify-between py-1 border-b border-slate-100 text-xs">
                  <div>
                    <span className="font-medium">{v.guarantor_name}</span>
                    <span className="text-slate-400 ml-2">({v.guarantor_relationship || '—'})</span>
                  </div>
                  <span className={`px-2 py-0.5 rounded-full border text-[10px] font-medium
                    ${v.status === 'approved' ? 'bg-emerald-50 text-emerald-700 border-emerald-200'
                      : v.status === 'rejected' ? 'bg-rose-50 text-rose-700 border-rose-200'
                      : 'bg-slate-100 text-slate-600 border-slate-200'}`}>
                    {v.status?.replace(/_/g, ' ') || 'pending'}
                  </span>
                </div>
              ))}
            </div>
          </>
        )}

        {/* 9. FIDELITY BONDS */}
        {fidelityBonds.length > 0 && (
          <>
            <SectionTitle title="Fidelity Bonds" number={9} />
            <div className="grid grid-cols-2 gap-3">
              {fidelityBonds.map((f) => (
                <div key={f.id} className="border border-slate-200 rounded p-2">
                  <p className="text-xs font-medium text-slate-800">{f.surety_name}</p>
                  <p className="text-[11px] text-slate-500">Relationship: {f.relationship || '—'}</p>
                </div>
              ))}
            </div>
          </>
        )}

        {/* FOOTER */}
        <div className="mt-8 pt-4 border-t border-slate-200 flex items-end justify-between">
          <div>
            <p className="text-[10px] text-slate-400">Printed on {generatedAt} from InfinityCore HR</p>
            <p className="text-[10px] text-slate-400">Record ID: {recordId} · For internal HR use only</p>
          </div>
          <div className="text-right">
            <div className="w-32 border-b border-slate-300 mb-1" />
            <p className="text-[10px] text-slate-400">Authorized Signature</p>
          </div>
        </div>
      </div>
    </div>
  )
}