-- ===========================================================================
-- Chairman + MD/CEO executive roles, and department-title hygiene.
--
-- Run in the Supabase SQL Editor AFTER 20260924000002 (and after
-- 20260924000001_director_executive_intelligence.sql). Idempotent + additive,
-- transaction-wrapped. Nothing is dropped and no historical row is rewritten.
--
-- 1) MD/CEO (`md_ceo`) and Chairman (`chairman`) are added as platform roles
--    with EXACTLY the same access profile as Director: the read-only
--    `director.executive.read` workspace + self-service attendance. The Director
--    role was seeded with only `director.executive.read`, so its granular
--    attendance/leave baseline was silently missing (default-deny in
--    public._permission_state); the baseline below repairs that for all three.
-- 2) Role assignment stays protected: only super_admin/admin may grant the
--    executive viewer roles (mirrors the invite-employees / create-user edge
--    function gates, so there is no second authorization system).
-- 3) Executive TITLES are not departments. `public.is_role_like_department()`
--    and `public.department_label()` are the server-side source of truth; the
--    department option lists in get_dashboard_filter_options() and
--    get_director_executive_snapshot() no longer offer "MD/CEO", and stored
--    title values are reported as "Unassigned" instead of being presented as a
--    department. Stored employee data is NEVER overwritten — HR still decides
--    which real department an executive belongs to.
-- ===========================================================================
begin;

-- ---------------------------------------------------------------------------
-- 1. Department-title helpers (pure, immutable, no data access).
-- ---------------------------------------------------------------------------
create or replace function public.is_role_like_department(p_value text)
returns boolean language sql immutable set search_path = public as $$
  select upper(regexp_replace(btrim(coalesce(p_value, '')), '\s+', ' ', 'g')) = any (array[
    'MD','M.D','M.D.','MD/CEO','MD, CEO','MD & CEO','MD / CEO','CEO',
    'MANAGING DIRECTOR','MANAGING DIRECTOR/CEO','CHAIRMAN','CHAIRMAN/CEO',
    'DIRECTOR','BOARD','BOARD OF DIRECTORS'
  ]);
$$;
revoke all on function public.is_role_like_department(text) from public;

-- Canonical label for a department value: an executive title is not a
-- department, so it falls into the honest "Unassigned" bucket instead of
-- inventing a department nobody owns.
create or replace function public.department_label(p_value text)
returns text language sql immutable set search_path = public as $$
  select case
    when public.is_role_like_department(p_value) then 'Unassigned'
    else coalesce(nullif(btrim(p_value), ''), 'Unassigned')
  end;
$$;
revoke all on function public.department_label(text) from public;

-- ---------------------------------------------------------------------------
-- 2. Platform roles.
-- ---------------------------------------------------------------------------
insert into public.roles (role_name, display_name, description, is_system_role, color, icon)
values
  ('md_ceo', 'MD/CEO', 'Managing Director / Chief Executive Officer — read-only executive intelligence across the entire bank', true, '#0f172a', 'crown'),
  ('chairman', 'Chairman', 'Board-level read-only executive intelligence across the entire bank', true, '#1e293b', 'crown')
on conflict (role_name) do update set
  display_name = excluded.display_name,
  description = excluded.description,
  is_system_role = true,
  color = excluded.color,
  icon = excluded.icon;

alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check (role in (
  'super_admin','admin','md_ceo','chairman','director','head_of_business','area_manager','branch_manager',
  'head_of_operations','head_of_e_business','financial_controller',
  'head_of_risk_compliance','head_of_legal','head_of_audit',
  'loan_officer','relationship_manager','customer_service',
  'head_of_human_resources','hr_officer','staff','customer'
));

-- ---------------------------------------------------------------------------
-- 3. Granular privilege baseline — identical for md_ceo, chairman and director.
--    Generated by scripts/gen-privilege-seed.mjs from src/constants/roles.js so
--    the catalog, the role matrix and the UI can never drift.
-- ---------------------------------------------------------------------------
select public.seed_permission('attendance.clock_in', 'Clock in on Attendance (attendance.clock_in)', 'attendance', 'attendance', 'clock_in', false, 'attendance');
select public.seed_permission('attendance.clock_out', 'Clock out on Attendance (attendance.clock_out)', 'attendance', 'attendance', 'clock_out', false, 'attendance');
select public.seed_permission('attendance.history', 'History on Attendance (attendance.history)', 'attendance', 'attendance', 'history', false, 'attendance');
select public.seed_permission('attendance.view', 'View on Attendance (attendance.view)', 'attendance', 'attendance', 'view', false, 'attendance');
select public.seed_permission('director.executive.read', 'Read on executive (director.executive.read)', 'director', 'executive', 'read', false, 'director');
select public.seed_permission('hr.attendance.self', 'Self on attendance (hr.attendance.self)', 'hr', 'attendance', 'self', false, 'hr');
select public.seed_permission('hr.leave.request', 'Request on leave (hr.leave.request)', 'hr', 'leave', 'request', false, 'hr');
select public.seed_permission('hr.leave.view', 'View on leave (hr.leave.view)', 'hr', 'leave', 'view', false, 'hr');
select public.seed_permission('messaging.attachments.upload', 'Upload on attachments (messaging.attachments.upload)', 'messaging', 'attachments', 'upload', false, 'messaging');
select public.seed_permission('messaging.send', 'Send on Messaging (messaging.send)', 'messaging', 'messaging', 'send', false, 'messaging');
select public.seed_permission('messaging.view', 'View on Messaging (messaging.view)', 'messaging', 'messaging', 'view', false, 'messaging');
select public.seed_permission('sara.use', 'Use on SARA (sara.use)', 'sara', 'sara', 'use', false, 'sara');
select public.seed_role_permission('md_ceo', 'director.executive.read');
select public.seed_role_permission('md_ceo', 'hr.attendance.self');
select public.seed_role_permission('md_ceo', 'attendance.view');
select public.seed_role_permission('md_ceo', 'attendance.clock_in');
select public.seed_role_permission('md_ceo', 'attendance.clock_out');
select public.seed_role_permission('md_ceo', 'attendance.history');
select public.seed_role_permission('md_ceo', 'messaging.view');
select public.seed_role_permission('md_ceo', 'messaging.send');
select public.seed_role_permission('md_ceo', 'messaging.attachments.upload');
select public.seed_role_permission('md_ceo', 'sara.use');
select public.seed_role_permission('md_ceo', 'hr.leave.view');
select public.seed_role_permission('md_ceo', 'hr.leave.request');
select public.seed_role_permission('chairman', 'director.executive.read');
select public.seed_role_permission('chairman', 'hr.attendance.self');
select public.seed_role_permission('chairman', 'attendance.view');
select public.seed_role_permission('chairman', 'attendance.clock_in');
select public.seed_role_permission('chairman', 'attendance.clock_out');
select public.seed_role_permission('chairman', 'attendance.history');
select public.seed_role_permission('chairman', 'messaging.view');
select public.seed_role_permission('chairman', 'messaging.send');
select public.seed_role_permission('chairman', 'messaging.attachments.upload');
select public.seed_role_permission('chairman', 'sara.use');
select public.seed_role_permission('chairman', 'hr.leave.view');
select public.seed_role_permission('chairman', 'hr.leave.request');
select public.seed_role_permission('director', 'director.executive.read');
select public.seed_role_permission('director', 'hr.attendance.self');
select public.seed_role_permission('director', 'attendance.view');
select public.seed_role_permission('director', 'attendance.clock_in');
select public.seed_role_permission('director', 'attendance.clock_out');
select public.seed_role_permission('director', 'attendance.history');
select public.seed_role_permission('director', 'messaging.view');
select public.seed_role_permission('director', 'messaging.send');
select public.seed_role_permission('director', 'messaging.attachments.upload');
select public.seed_role_permission('director', 'sara.use');
select public.seed_role_permission('director', 'hr.leave.view');
select public.seed_role_permission('director', 'hr.leave.request');

-- ---------------------------------------------------------------------------
-- 4. Role-change protection: executive viewer roles are senior roles.
-- ---------------------------------------------------------------------------
create or replace function public.enforce_role_change_policy()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  actor_role text := public.current_role();
  promoter_roles text[] := array['super_admin','admin','head_of_human_resources','area_manager','branch_manager'];
  senior_roles text[] := array['md_ceo','chairman','director'];
  management_roles text[] := array[
    'admin','md_ceo','chairman','director','area_manager','head_of_business','head_of_operations',
    'head_of_e_business','financial_controller','head_of_risk_compliance','head_of_legal','head_of_audit'
  ];
begin
  if new.role is distinct from old.role then
    if not (actor_role = any(promoter_roles)) then
      raise exception 'Not authorized to change roles (actor role: %)', actor_role;
    end if;
    if new.role = 'super_admin' and actor_role <> 'super_admin' then
      raise exception 'Only super_admin can assign the super_admin role';
    end if;
    if new.role = any(senior_roles) and actor_role not in ('super_admin','admin') then
      raise exception 'Only super_admin or admin can assign the % role', new.role;
    end if;
    if new.role = any(management_roles) and actor_role not in ('super_admin','admin') then
      raise exception 'Only super_admin or admin can assign this role';
    end if;
    if actor_role = 'branch_manager' and new.role not in ('staff','loan_officer','relationship_manager','customer_service') then
      raise exception 'Branch Manager is not authorized to assign this role';
    end if;
    insert into public.audit_logs (action, entity_type, entity_id, user_name, details, severity)
    values ('user_role_changed','User',new.id::text,
      coalesce((select full_name from public.profiles where id = auth.uid()),auth.uid()::text),
      format('%s: %s -> %s',coalesce(new.email,new.id::text),old.role,new.role),'critical');
  end if;
  return new;
end;
$$;

drop trigger if exists trg_enforce_role_change on public.profiles;
create trigger trg_enforce_role_change before update on public.profiles
for each row execute function public.enforce_role_change_policy();

-- ---------------------------------------------------------------------------
-- 5. Department option lists — executive titles removed.
--    Bodies are the latest definitions with ONLY the department-label logic
--    changed (get_dashboard_filter_options from 20260921000010; the two director
--    RPCs from 20260924000001 plus the widened executive role gate).
-- ---------------------------------------------------------------------------
create or replace function public.get_dashboard_filter_options(
  p_branch_id uuid default null,
  p_department text default null,
  p_area text default null
)
returns jsonb
language plpgsql security definer stable set search_path = public as $$
declare
  v_role text := public.current_role();
  v_me public.employees%rowtype;
  v_org_scope boolean := false;
  v_branch_scope uuid;
  v_area_scope text;
  v_employee_scope uuid;
begin
  if auth.uid() is null then raise exception 'Not authenticated'; end if;
  select * into v_me from public.employees where user_id = auth.uid() order by created_at desc limit 1;
  v_org_scope := v_role in ('super_admin', 'admin', 'head_of_human_resources', 'hr_officer', 'head_of_business')
    or upper(trim(coalesce(v_me."position", ''))) in ('MD', 'MD/CEO');

  if v_role = 'branch_manager' then
    v_branch_scope := v_me.branch_id;
    if p_branch_id is not null and p_branch_id is distinct from v_branch_scope then
      raise exception 'Not authorized for this branch';
    end if;
    if v_branch_scope is null then v_employee_scope := v_me.id; end if;
  elsif v_role = 'area_manager' then
    v_area_scope := v_me.area;
    if p_area is not null and lower(p_area) <> lower(coalesce(v_area_scope, '')) then
      raise exception 'Not authorized for this area';
    end if;
    if v_area_scope is null then v_employee_scope := v_me.id; end if;
  elsif not v_org_scope then
    v_employee_scope := v_me.id;
  end if;

  return jsonb_build_object(
    'branches', coalesce((
      select jsonb_agg(jsonb_build_object('id', b.id, 'branch_name', b.branch_name, 'branch_code', b.branch_code) order by b.branch_name)
      from public.branches b
      where b.status = 'active'
        and (v_org_scope or v_me.id is not null)
        and (v_branch_scope is null or b.id = v_branch_scope)
        and (v_area_scope is null or exists (
          select 1 from public.branch_area_assignments baa
          join public.areas a on a.id = baa.area_id
          where baa.branch_id = b.id and baa.is_current and lower(a.area_code) = lower(v_area_scope)
        ))
    ), '[]'::jsonb),
    'areas', coalesce((
      select jsonb_agg(jsonb_build_object('id', a.id, 'area_code', a.area_code, 'area_name', a.area_name) order by a.area_code)
      from public.areas a
      where a.is_active
        and (v_org_scope or v_me.id is not null)
        and (v_area_scope is null or lower(a.area_code) = lower(v_area_scope))
        and (v_branch_scope is null or exists (
          select 1 from public.branch_area_assignments baa
          where baa.area_id = a.id and baa.branch_id = v_branch_scope and baa.is_current
        ))
    ), '[]'::jsonb),
    'departments', coalesce((
      select jsonb_agg(jsonb_build_object('id', x.name, 'name', x.name) order by x.name)
      from (
      select distinct public.department_label(e.department) as name
        from public.employees e
        where coalesce(e.is_archived, false) = false
          and not public.is_role_like_department(e.department)
          and (v_org_scope or v_me.id is not null)
          and (v_employee_scope is null or e.id = v_employee_scope)
          and (v_branch_scope is null or e.branch_id = v_branch_scope)
          and (v_area_scope is null or lower(coalesce(e.area, '')) = lower(v_area_scope))
          and (p_branch_id is null or e.branch_id = p_branch_id)
          and (p_area is null or lower(coalesce(e.area, '')) = lower(p_area))
      ) x
    ), '[]'::jsonb),
    'employees', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', x.id, 'full_name', x.full_name, 'department', x.department,
        'branch_id', x.branch_id, 'branch', x.branch, 'area', x.area
      ) order by x.full_name)
      from (
        select e.id, e.full_name, public.department_label(e.department) as department, e.branch_id, e.branch, e.area
        from public.employees e
        where coalesce(e.is_archived, false) = false
          and (v_org_scope or v_me.id is not null)
          and (v_employee_scope is null or e.id = v_employee_scope)
          and (v_branch_scope is null or e.branch_id = v_branch_scope)
          and (v_area_scope is null or lower(coalesce(e.area, '')) = lower(v_area_scope))
          and (p_branch_id is null or e.branch_id = p_branch_id)
          and (p_department is null or lower(coalesce(e.department, '')) = lower(p_department))
          and (p_area is null or lower(coalesce(e.area, '')) = lower(p_area))
        order by e.full_name
        limit 500
      ) x
    ), '[]'::jsonb)
  );
end;
$$;

revoke all on function public.get_dashboard_filter_options(uuid, text, text) from public;
grant execute on function public.get_dashboard_filter_options(uuid, text, text) to authenticated;

create or replace function public.get_director_executive_snapshot(
  p_start_date date default null, p_end_date date default null,
  p_department text default null, p_branch_id uuid default null,
  p_area text default null, p_role text default null,
  p_designation_id uuid default null, p_employee_id uuid default null
) returns jsonb language plpgsql stable security definer set search_path = public as $$
declare
  v_end date := coalesce(p_end_date, current_date);
  v_start date := coalesce(p_start_date, date_trunc('month', current_date)::date);
  v_previous_end date := v_start - 1;
  v_previous_start date := v_start - (v_end - v_start + 1);
  v_result jsonb;
begin
  if auth.uid() is null then raise exception 'Not authenticated'; end if;
  if public.current_role() not in ('md_ceo','chairman','director','super_admin')
     or not public.has_permission('director.executive.read') then
    raise exception 'insufficient_permissions: director.executive.read';
  end if;
  if v_end < v_start or v_end > current_date or v_start < current_date - interval '2 years' then
    raise exception 'Invalid executive reporting period';
  end if;

  with scoped as (
    select e.*, b.branch_name, d.title as designation_title,
      coalesce(nullif(e.area,''),(select coalesce(a.area_name,a.area_code) from public.branch_area_assignments baa
        join public.areas a on a.id=baa.area_id where baa.branch_id=e.branch_id and baa.is_current limit 1)) area_name,
      coalesce(p.role,'staff') platform_role,
      public.department_label(e.department) department_label,
      (select doc.file_path from public.documents doc where doc.entity_type='employee' and doc.entity_id=e.id
        and lower(coalesce(doc.document_type,''))='profile_picture' order by doc.created_at desc limit 1) profile_picture_path
    from public.employees e
    left join public.profiles p on p.id=e.user_id
    left join public.branches b on b.id=e.branch_id
    left join public.designations d on d.id=e.designation_id
    where (p_department is null or lower(coalesce(e.department,''))=lower(p_department))
      and (p_branch_id is null or e.branch_id=p_branch_id)
      and (p_area is null or lower(coalesce(e.area,''))=lower(p_area)
        or exists (select 1 from public.branch_area_assignments baa join public.areas a on a.id=baa.area_id
          where baa.branch_id=e.branch_id and baa.is_current and lower(coalesce(a.area_name,a.area_code))=lower(p_area)))
      and (p_role is null or coalesce(p.role,'staff')=p_role)
      and (p_designation_id is null or e.designation_id=p_designation_id)
      and (p_employee_id is null or e.id=p_employee_id)
  ), ids as (select id from scoped), range_days as (
    select series_date::date as attendance_date
    from generate_series(v_start::timestamp, v_end::timestamp, interval '1 day') as dates(series_date)
    where extract(isodow from series_date::date) < 6
  ), attendance as (
    select * from public.attendance_records where employee_id in (select id from ids) and attendance_date between v_start and v_end
  ), previous_attendance as (
    select * from public.attendance_records where employee_id in (select id from ids) and attendance_date between v_previous_start and v_previous_end
  ), kpis as (
    select * from public.employee_kpis where employee_id in (select id from ids) and coalesce(updated_at,created_at)::date between v_start and v_end
  ), previous_kpis as (
    select * from public.employee_kpis where employee_id in (select id from ids) and coalesce(updated_at,created_at)::date between v_previous_start and v_previous_end
  ), targets as (
    select * from public.targets where employee_id in (select id from ids) and coalesce(start_date,created_at::date)<=v_end
      and coalesce(end_date,'infinity'::date)>=v_start and status not in ('cancelled','missed')
  ), leave_rows as (
    select lr.*, e.id employee_id from public.leave_requests lr join public.employees e on e.user_id=lr.created_by where e.id in (select id from ids)
  ), staff as (
    select s.*,
      (select count(*) from attendance a where a.employee_id=s.id and a.clock_in is not null)::int attendance_present,
      (select count(*) from previous_attendance a where a.employee_id=s.id and a.clock_in is not null)::int previous_attendance_present,
      (select count(*) from range_days)::int expected_days,
      (select count(*) from kpis k where k.employee_id=s.id)::int kpi_count,
      (select count(*) from kpis k where k.employee_id=s.id and k.status in ('completed','acknowledged'))::int kpi_completed,
      (select count(*) from targets t where t.employee_id=s.id)::int target_count,
      (select count(*) from targets t where t.employee_id=s.id and t.status='achieved')::int target_achieved,
      (select count(*) from leave_rows l where l.employee_id=s.id and l.status='approved' and l.start_date<=v_end and l.end_date>=v_start)::int leave_count
    from scoped s
  ), overall as (
    select count(*)::int total_staff, count(*) filter(where employment_status='active')::int active_staff,
      count(*) filter(where employment_status='on_leave' or leave_count>0)::int on_leave,
      coalesce(round(100.0*sum(attendance_present)/nullif(sum(expected_days),0)),0) attendance_rate,
      coalesce(round(100.0*sum(previous_attendance_present)/nullif(sum(expected_days),0)),0) previous_attendance_rate,
      coalesce(round(100.0*sum(kpi_completed)/nullif(sum(kpi_count),0)),0) kpi_completion,
      coalesce(round(100.0*sum(target_achieved)/nullif(sum(target_count),0)),0) target_completion from staff
  ), perf as (
    select coalesce(round(avg(least(200,100.0*actual_value/nullif(target_value,0))),1),0) achievement_pct from kpis where target_value<>0
  ), previous_perf as (
    select coalesce(round(avg(least(200,100.0*actual_value/nullif(target_value,0))),1),0) achievement_pct from previous_kpis where target_value<>0
  ), target_perf as (
    select coalesce(round(100.0*sum(current_value)/nullif(sum(target_value),0),1),0) achievement_pct from targets where target_value<>0
  )
  select jsonb_build_object(
    'generated_at',now(),'range',jsonb_build_object('start',v_start,'end',v_end,'previous_start',v_previous_start,'previous_end',v_previous_end),
    'summary',(select to_jsonb(o) from overall o) || jsonb_build_object(
      'absent',(select coalesce(sum(expected_days-attendance_present),0)::int from staff where employment_status='active' and leave_count=0),
      'kpi_achievement',(select achievement_pct from perf),'previous_kpi_achievement',(select achievement_pct from previous_perf),
      'target_achievement',(select achievement_pct from target_perf),
      'loans_disbursed',(select coalesce(sum(principal_amount),0) from public.loans where coalesce(disbursed_date,created_at::date) between v_start and v_end),
      'previous_loans_disbursed',(select coalesce(sum(principal_amount),0) from public.loans where coalesce(disbursed_date,created_at::date) between v_previous_start and v_previous_end),
      'loan_portfolio',(select coalesce(sum(outstanding_balance),0) from public.loans where status in ('active','disbursed','performing')),
      'repayments',(select coalesce(sum(amount),0) from public.repayments where payment_date between v_start and v_end),
      'previous_repayments',(select coalesce(sum(amount),0) from public.repayments where payment_date between v_previous_start and v_previous_end),
      'active_recruitment',(select count(*) from public.hr_candidates where application_status not in ('hired','rejected','withdrawn')),
      'open_onboarding',(select count(*) from public.employee_onboarding_submissions where onboarding_status in ('submitted','under_review','pending_guarantor','guarantor_submitted','correction_requested')),
      'pending_leave',(select count(*) from leave_rows where status='pending'),
      'upcoming_resumptions',(select count(*) from leave_rows where status='approved' and end_date between v_end and v_end+14)
    ),
    'filters',jsonb_build_object(
      'departments',(select coalesce(jsonb_agg(jsonb_build_object('id',x.name,'name',x.name) order by x.name),'[]') from (select distinct public.department_label(e.department) name from public.employees e) x where x.name <> 'Unassigned'),
      'branches',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',branch_name) order by branch_name),'[]') from public.branches where coalesce(status,'active')='active'),
      'areas',(select coalesce(jsonb_agg(jsonb_build_object('id',area_code,'name',coalesce(area_name,area_code)) order by area_code),'[]') from public.areas where is_active),
      'roles',(select coalesce(jsonb_agg(jsonb_build_object('id',role,'name',role) order by role),'[]') from (select distinct role from public.profiles) x),
      'designations',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',title,'department',department) order by title,department),'[]') from public.designations where is_active),
      'employees',(select coalesce(jsonb_agg(jsonb_build_object('id',e.id,'name',e.full_name,'department',public.department_label(e.department),'branch',b.branch_name) order by e.full_name),'[]') from public.employees e left join public.branches b on b.id=e.branch_id)
    ),
    'departments',(select coalesce(jsonb_agg(x order by (x->>'total_staff')::int desc),'[]') from (
      select jsonb_build_object('id',department_label,'name',department_label,'total_staff',count(*),'active_staff',count(*) filter(where employment_status='active'),'attendance_rate',coalesce(round(100.0*sum(attendance_present)/nullif(sum(expected_days),0)),0),'kpi_completion',coalesce(round(100.0*sum(kpi_completed)/nullif(sum(kpi_count),0)),0),'target_completion',coalesce(round(100.0*sum(target_achieved)/nullif(sum(target_count),0)),0),'on_leave',count(*) filter(where leave_count>0),'completion_rate',coalesce(round((sum(attendance_present)+sum(kpi_completed)+sum(target_achieved))*100.0/nullif(sum(expected_days)+sum(kpi_count)+sum(target_count),0)),0)) x
      from staff group by department_label) x),
    'branches',(select coalesce(jsonb_agg(x order by (x->>'total_staff')::int desc),'[]') from (
      select jsonb_build_object('id',coalesce(branch_name,'Unassigned'),'name',coalesce(branch_name,'Unassigned'),'total_staff',count(*),'active_staff',count(*) filter(where employment_status='active'),'attendance_rate',coalesce(round(100.0*sum(attendance_present)/nullif(sum(expected_days),0)),0),'kpi_completion',coalesce(round(100.0*sum(kpi_completed)/nullif(sum(kpi_count),0)),0),'target_completion',coalesce(round(100.0*sum(target_achieved)/nullif(sum(target_count),0)),0),'on_leave',count(*) filter(where leave_count>0)) x
      from staff group by coalesce(branch_name,'Unassigned')) x),
    'areas',(select coalesce(jsonb_agg(x order by (x->>'total_staff')::int desc),'[]') from (
      select jsonb_build_object('id',coalesce(area_name,'Unassigned'),'name',coalesce(area_name,'Unassigned'),'total_staff',count(*),'active_staff',count(*) filter(where employment_status='active'),'attendance_rate',coalesce(round(100.0*sum(attendance_present)/nullif(sum(expected_days),0)),0),'kpi_completion',coalesce(round(100.0*sum(kpi_completed)/nullif(sum(kpi_count),0)),0),'target_completion',coalesce(round(100.0*sum(target_achieved)/nullif(sum(target_count),0)),0),'on_leave',count(*) filter(where leave_count>0)) x
      from staff group by coalesce(area_name,'Unassigned')) x),
    'staff',(select coalesce(jsonb_agg(to_jsonb(x) order by full_name),'[]') from (select id,user_id,full_name,profile_picture_path,platform_role,department_label as department,branch_name,area_name,"position",designation_title,hire_date,employment_status,leave_count,attendance_present,expected_days,case when expected_days>0 then round(100.0*attendance_present/expected_days) end attendance_rate,kpi_completed,kpi_count,target_achieved,target_count from staff) x),
    'leave',(select coalesce(jsonb_agg(to_jsonb(x) order by end_date),'[]') from (
      select l.id,l.employee_id,e.full_name,public.department_label(e.department) as department,e."position",l.leave_type,l.start_date,l.end_date,l.status,greatest(0,l.end_date-current_date) days_remaining
      from leave_rows l join public.employees e on e.id=l.employee_id
      where l.status='approved' and l.start_date<=v_end and l.end_date>=v_start
      union all
      select l.id,l.employee_id,e.full_name,public.department_label(e.department) as department,e."position",l.leave_type,l.start_date,l.end_date,l.status,0
      from leave_rows l join public.employees e on e.id=l.employee_id where l.status in ('pending','rejected') order by 1) x),
    'roles',(select coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)->>'role'),'[]') from (
      select platform_role role,count(*) staff,coalesce(round(100.0*sum(attendance_present)/nullif(sum(expected_days),0)),0) attendance_rate,
        coalesce(round(100.0*sum(kpi_completed)/nullif(sum(kpi_count),0)),0) kpi_completion,
        coalesce(round(100.0*sum(target_achieved)/nullif(sum(target_count),0)),0) target_completion from staff group by platform_role) x),
    'trend',(select coalesce(jsonb_agg(to_jsonb(x) order by attendance_date),'[]') from (
      select d.attendance_date,coalesce(round(100.0*count(a.id) filter(where a.clock_in is not null)/nullif(count(s.id),0)),0) attendance_rate
      from range_days d cross join staff s left join attendance a on a.employee_id=s.id and a.attendance_date=d.attendance_date group by d.attendance_date) x),
    'loans',jsonb_build_object('status',jsonb_build_object(
      'count',(select count(*) from public.loans where coalesce(disbursed_date,created_at::date) between v_start and v_end),
      'principal',(select coalesce(sum(principal_amount),0) from public.loans where coalesce(disbursed_date,created_at::date) between v_start and v_end),
      'outstanding',(select coalesce(sum(outstanding_balance),0) from public.loans)))
  ) into v_result;
  return v_result;
end;
$$;

revoke all on function public.get_director_executive_snapshot(date,date,text,uuid,text,text,uuid,uuid) from public;
grant execute on function public.get_director_executive_snapshot(date,date,text,uuid,text,text,uuid,uuid) to authenticated;

create or replace function public.get_director_employee_detail(p_employee_id uuid)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare v_result jsonb;
begin
  if public.current_role() not in ('md_ceo','chairman','director','super_admin') or not public.has_permission('director.executive.read') then
    raise exception 'insufficient_permissions: director.executive.read';
  end if;
  select jsonb_build_object(
    'profile',(select jsonb_build_object('id',e.id,'full_name',e.full_name,'department',public.department_label(e.department),'position',e."position",'designation',d.title,'branch',coalesce(b.branch_name,e.branch),'area',coalesce(e.area,a.area_name),'hire_date',e.hire_date,'status',e.employment_status,'role',coalesce(p.role,'staff')) from public.employees e left join public.profiles p on p.id=e.user_id left join public.branches b on b.id=e.branch_id left join public.designations d on d.id=e.designation_id left join public.branch_area_assignments baa on baa.branch_id=e.branch_id and baa.is_current left join public.areas a on a.id=baa.area_id where e.id=p_employee_id),
    'kpis',(select coalesce(jsonb_agg(to_jsonb(k) order by updated_at desc),'[]') from public.employee_kpis k where k.employee_id=p_employee_id),
    'targets',(select coalesce(jsonb_agg(to_jsonb(t) order by end_date desc),'[]') from public.targets t where t.employee_id=p_employee_id),
    'attendance',(select coalesce(jsonb_agg(to_jsonb(a) order by attendance_date desc),'[]') from (select * from public.attendance_records where employee_id=p_employee_id order by attendance_date desc limit 90) a),
    'leave',(select coalesce(jsonb_agg(to_jsonb(l) order by start_date desc),'[]') from public.leave_requests l join public.employees e on e.user_id=l.created_by where e.id=p_employee_id)
  ) into v_result;
  return coalesce(v_result,'{}'::jsonb);
end;
$$;

revoke all on function public.get_director_employee_detail(uuid) from public;
grant execute on function public.get_director_employee_detail(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- 6. Master data hygiene: a departments row named after an executive title is
--    deactivated so it stops being offered as a department anywhere. No row is
--    deleted and no employee is reassigned — HR assigns the real department.
-- ---------------------------------------------------------------------------
do $$
declare
  v_row record;
begin
  for v_row in
    select id, name from public.departments
    where coalesce(is_active, true) and public.is_role_like_department(name)
  loop
    update public.departments set is_active = false where id = v_row.id;
    insert into public.audit_logs (action, entity_type, entity_id, user_name, details, severity)
    values ('DEPARTMENT_TITLE_DEACTIVATED','Department',v_row.id::text,'system',
      format('%s is an executive title (a role), not a department — deactivated as a department option', v_row.name),'warning');
  end loop;
end $$;

commit;
