-- ============================================================================
-- 20261101000007a — STAGING SCHEMA for the authoritative employee replace
-- ============================================================================
--
--   ##  RUN THIS FIRST.  ##
--
--   ##  It is safe to re-run.  ##
--
-- The three generated value files (employee_source_values.sql,
-- employee_branch_values.sql, employee_supervisor_values.sql) are plain
-- INSERTs into the stg_* tables, so those tables MUST already exist before
-- they are loaded. The replace script also creates them (idempotently) but it
-- can only run AFTER the data is loaded, so this file exists to break that
-- chicken-and-egg problem: run this, then the three value files, then the
-- replace script.
--
-- Purely additive: creates seven staging tables and one index. No existing
-- table is read or modified, and nothing here depends on any employee data.
--
-- RUN ORDER: this file FIRST, then the four org_*_values.sql files, then the
-- three employee_*_values.sql files, then 20261101000010, then 20261101000008.
-- As a safety net the value files below ALSO create their own target table
-- (IF NOT EXISTS, matching this schema exactly), so running them first by
-- accident no longer fails with "relation does not exist" — you can simply
-- run this file afterwards and re-run the value files to fill the gaps.
-- ============================================================================

create table if not exists public.stg_hr_employee_source (
  staff_id text primary key,
  full_name text not null,
  first_name text,
  last_name text,
  email text,
  position text,
  department text,
  gender text,
  confirmation_status text,
  source_row jsonb
);

create table if not exists public.stg_hr_employee_branch_source (
  staff_id text not null,
  branch_label text not null
);

create unique index if not exists uq_stg_branch
  on public.stg_hr_employee_branch_source (staff_id, branch_label);

create table if not exists public.stg_hr_employee_supervisor_source (
  staff_id text primary key,
  supervisor_1 text,
  supervisor_2 text,
  supervisor_3 text
);

-- ---------------------------------------------------------------------------
-- ORGANISATIONAL MASTER (generated by scripts/build-authoritative-org.mjs)
-- ---------------------------------------------------------------------------
-- The workbook is already cleaned; the database is not. These four tables carry
-- the TARGET state plus an explicit collapse map, so the apply script can repair
-- the dirty `branches` rows the bank master left behind
-- (BARIGA/LAGOS Island 1, KETU & HEAD OFFICE, ...) rather than aliasing workbook
-- labels onto whatever happens to exist today.

-- The 21 canonical branches, verbatim from the workbook "Branches" sheet.
create table if not exists public.stg_hr_branch_source (
  branch_name text primary key,
  branch_code text
);

-- Every branch spelling we have ever seen -> the canonical branch it becomes.
-- A row with target_name = '' is a spelling NOT present in the workbook; the apply
-- script DEACTIVATES it rather than guessing where it belongs.
--
-- target_name is an empty string rather than NULL on purpose: this table has a
-- PRIMARY KEY (existing_name, target_name), and a NULL in a PK column is not
-- permitted — PostgreSQL would reject the whole value file with
-- "null value in column target_name ... violates not-null constraint".
-- '' therefore means "no destination", which is unambiguous and indexable.
create table if not exists public.stg_hr_branch_collapse (
  existing_name text not null,
  target_name text not null default '',
  primary key (existing_name, target_name)
);

-- The 13 departments (executive titles such as MD/CEO are excluded).
create table if not exists public.stg_hr_department_source (
  name text primary key,
  code text,
  sort_order int
);

-- The 66 designations, verbatim from the workbook "Positions" sheet.
create table if not exists public.stg_hr_designation_source (
  title text primary key,
  sort_order int
);